use std::collections::BTreeSet;

use signal_domain::{
    DOMAIN_INTERFACE_RUST, DOMAIN_INTERFACE_SOURCE,
    bootstrap_manifest::{
        BOOLEAN_SEAT, DECLARATION_SEATS, INPUT_SEAT, INTEGER_SEAT, INTERFACE_SEAT, MAP_SEAT,
        NEXUS_SEAT, OPTION_SEAT, OUTPUT_SEAT, REFUSAL_SEAT, RESULT_SEAT, SCOPEOF_SEAT, SEMA_SEAT,
        STREAM_SEAT, STREAMIDENTITY_SEAT, STRING_SEAT, UNIT_SEAT, VECTOR_SEAT,
    },
};

#[test]
fn canonical_source_is_the_interface_envelope() {
    assert!(DOMAIN_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  ["));
    assert!(DOMAIN_INTERFACE_SOURCE.ends_with("]\n}\n"));
    assert!(DOMAIN_INTERFACE_SOURCE.contains("Domain.["));
    assert!(DOMAIN_INTERFACE_SOURCE.contains("DomainScope.ScopeOf<Domain>"));
    assert!(DOMAIN_INTERFACE_SOURCE.contains("DomainScopes.Vector<DomainScope>"));
    assert!(!DOMAIN_INTERFACE_SOURCE.starts_with("{}"));

    let conceptual_order = [
        "Domain.[",
        "HealthDomain.[",
        "TechnologyDomain.[",
        "HardwareLeaf.[",
        "SoftwareDomain.[",
        "ProgrammingLeaf.[",
        "EngineeringLeaf.[",
        "DomainScope.ScopeOf<Domain>",
        "DomainScopes.Vector<DomainScope>",
        "ScopeSet.Vector<DomainScope>",
    ];
    let positions = conceptual_order.map(|declaration| {
        DOMAIN_INTERFACE_SOURCE
            .find(declaration)
            .unwrap_or_else(|| panic!("missing canonical declaration {declaration}"))
    });
    assert!(
        positions.windows(2).all(|pair| pair[0] < pair[1]),
        "authority ordering must preserve the conceptual taxonomy"
    );
    assert!(DOMAIN_INTERFACE_SOURCE.contains("Domain.[All Health.HealthDomain Food.FoodDomain"));
}

#[test]
fn authority_manifest_is_complete_and_opaque() {
    assert_eq!(DECLARATION_SEATS.len(), 410);
    assert_eq!(
        DECLARATION_SEATS
            .iter()
            .filter(|seat| seat.owner_local.is_none())
            .count(),
        41
    );
    assert_eq!(
        DECLARATION_SEATS
            .iter()
            .filter(|seat| seat.owner_local.is_some())
            .count(),
        369
    );

    let fixed = [
        INTERFACE_SEAT,
        NEXUS_SEAT,
        SEMA_SEAT,
        INPUT_SEAT,
        OUTPUT_SEAT,
        REFUSAL_SEAT,
        STRING_SEAT,
        INTEGER_SEAT,
        BOOLEAN_SEAT,
        UNIT_SEAT,
        VECTOR_SEAT,
        OPTION_SEAT,
        MAP_SEAT,
        RESULT_SEAT,
        STREAM_SEAT,
        STREAMIDENTITY_SEAT,
        SCOPEOF_SEAT,
    ];
    let locals = fixed
        .iter()
        .map(|seat| seat.local)
        .chain(DECLARATION_SEATS.iter().map(|seat| seat.local))
        .collect::<BTreeSet<_>>();
    let canonical = fixed
        .iter()
        .map(|seat| seat.canonical)
        .chain(DECLARATION_SEATS.iter().map(|seat| seat.canonical))
        .collect::<BTreeSet<_>>();
    assert_eq!(locals.len(), fixed.len() + DECLARATION_SEATS.len());
    assert_eq!(canonical.len(), fixed.len() + DECLARATION_SEATS.len());
    assert!(
        DECLARATION_SEATS
            .windows(2)
            .all(|pair| pair[0].canonical < pair[1].canonical),
        "manifest order is the deliberate canonical taxonomy order"
    );

    let owners = DECLARATION_SEATS
        .iter()
        .filter(|seat| seat.owner_local.is_none())
        .map(|seat| seat.local)
        .collect::<BTreeSet<_>>();
    assert!(
        DECLARATION_SEATS
            .iter()
            .filter_map(|seat| seat.owner_local)
            .all(|owner| owners.contains(&owner))
    );
}

#[test]
fn live_rust_is_the_strict_encoded_name_projection() {
    assert!(DOMAIN_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    assert_eq!(DOMAIN_INTERFACE_RUST.matches("pub enum ").count(), 38);
    assert_eq!(DOMAIN_INTERFACE_RUST.matches("pub struct ").count(), 3);
    for source_name in ["Domain", "HealthDomain", "DomainScope", "ScopeSet"] {
        assert!(
            !DOMAIN_INTERFACE_RUST.contains(&format!("pub enum {source_name}"))
                && !DOMAIN_INTERFACE_RUST.contains(&format!("pub struct {source_name}")),
            "source spelling {source_name} leaked into the encoded Rust namespace"
        );
    }
}
