// @generated by schema-rust from an authority-verified bootstrap source

pub enum Domain {
    All,
    Craft(CraftDomain),
    Knowledge(KnowledgeDomain),
    Travel(TravelDomain),
    Appearance(AppearanceDomain),
    Commerce(CommerceDomain),
    Spirituality(SpiritualityDomain),
    Work(WorkDomain),
    Technology(TechnologyDomain),
    Education(EducationDomain),
    Leisure(LeisureDomain),
    Language(LanguageDomain),
    Food(FoodDomain),
    Information(InformationDomain),
    Kinship(KinshipDomain),
    Art(ArtDomain),
    Health(HealthDomain),
    Community(CommunityDomain),
    Safety(SafetyDomain),
    Governance(GovernanceDomain),
    Selfhood(SelfhoodDomain),
    Finance(FinanceDomain),
    Nature(NatureDomain),
    Law(LawDomain),
    Home(HomeDomain),
}

pub enum QualityLeaf {
    Testing,
    All,
}

pub enum LeisureDomain {
    Hobby,
    Sport,
    Recreation,
    Relaxation,
    Entertainment,
    Fandom,
    Celebration,
    Collecting,
    Outdoors,
    Play,
    Games,
}

pub enum ArtDomain {
    Dance,
    Poetry,
    Photography,
    Painting,
    Music,
    Fiction,
    Creativity,
    Publishing,
    Sculpture,
    Design,
    Film,
    Theater,
    Storytelling,
}

pub enum InformationDomain {
    Broadcasting,
    Documentation,
    Retrieval,
    Classification,
    News,
    Curation,
    RecordKeeping,
    Archives,
    Database,
}

pub enum DistributedLeaf {
    All,
    ProtocolDesign,
    EventDrivenArchitecture,
}

pub enum IntelligenceLeaf {
    All,
    AgentSystems,
}

pub enum LawDomain {
    Custody,
    Justice,
    Rights,
    Procedure,
    Contract,
    Crime,
    Compliance,
    Litigation,
    Arbitration,
    Policing,
    Title,
    Liability,
}

pub enum EducationDomain {
    Mentoring,
    Studying,
    Skill,
    Memorization,
    Schooling,
    Reading,
    Teaching,
    Pedagogy,
    Credential,
    Autodidacticism,
}

pub enum SecurityLeaf {
    Cryptography,
    All,
    Authentication,
    SecretsManagement,
    Privacy,
    Authorization,
}

pub enum EngineeringLeaf {
    Architecture,
    Design,
    VersionControl,
    ApplicationProgrammingInterfaces,
    DevelopmentProcess,
    All,
    Modularity,
    Documentation,
    Management,
}

pub enum NatureDomain {
    Forestry,
    Gardening,
    Agriculture,
    Wilderness,
    Conservation,
    Fishing,
    Resources,
    Husbandry,
    Hunting,
    Horticulture,
    Stewardship,
    Weather,
    Pets,
    Sustainability,
}

pub enum DataLeaf {
    Serialization,
    SchemaEvolution,
    Migration,
    Formats,
    Persistence,
    Modeling,
    All,
}

pub enum KinshipDomain {
    Grief,
    Romance,
    Belonging,
    Marriage,
    Parenting,
    Boundaries,
    Family,
    Reconciliation,
    Relatives,
    Friendship,
    Rapport,
    Intimacy,
    Caregiving,
}

pub struct DomainScope(crate::Scope<Domain>);

pub enum ObservabilityLeaf {
    Tracing,
    All,
}

pub struct DomainScopes(Vec<DomainScope>);

pub enum SelfhoodDomain {
    Decision,
    Temperament,
    Emotion,
    Wellbeing,
    Virtue,
    Purpose,
    Growth,
    Identity,
    Motivation,
    Introspection,
    Composure,
    Discipline,
    Confidence,
}

pub enum FinanceDomain {
    Insurance,
    Retirement,
    Saving,
    Banking,
    Debt,
    Credit,
    Spending,
    Charity,
    Income,
    Accounting,
    Planning,
    Tax,
    Investing,
    Budgeting,
}

pub enum CraftDomain {
    Invention,
    Engineering,
    Carpentry,
    Electronics,
    Sewing,
    Metalworking,
    Manufacturing,
    Construction,
    Handicraft,
    Repair,
}

pub enum GovernanceDomain {
    Movements,
    Activism,
    Services,
    Administration,
    Policy,
    Naturalization,
    Organizing,
    Elections,
    Citizenship,
    Diplomacy,
    Politics,
    Government,
    War,
}

pub enum HealthDomain {
    Senses,
    Dentistry,
    Therapy,
    Sleep,
    Pain,
    Sexuality,
    Addiction,
    Aging,
    Reproduction,
    FirstAid,
    Exercise,
    Disease,
    Disability,
    Prevention,
    Medicine,
    Medication,
    Mind,
    Body,
    Rehabilitation,
    Nutrition,
}

pub enum AppearanceDomain {
    Etiquette,
    Grooming,
    Cosmetics,
    Style,
    Clothing,
    Comportment,
}

pub enum KnowledgeDomain {
    Statistics,
    Linguistics,
    Astronomy,
    Logic,
    Geology,
    Philosophy,
    Economics,
    Chemistry,
    Biology,
    Taxonomy,
    Computing,
    Mathematics,
    History,
    Physics,
    Cognition,
    Research,
    Physiology,
}

pub enum FoodDomain {
    Cooking,
    Entertaining,
    Preservation,
    Dining,
    Fermentation,
    Foraging,
    Recipe,
    Diet,
    Baking,
    Beverage,
    Fasting,
}

pub enum OperationsLeaf {
    Deployment,
    ConfigurationManagement,
    BuildSystem,
    ReleaseEngineering,
    DependencyManagement,
    All,
}

pub enum CommunityDomain {
    Membership,
    Institutions,
    Volunteering,
    Neighborliness,
    Hospitality,
    Service,
    Gatherings,
    Solidarity,
    Reputation,
}

pub enum SurfacesLeaf {
    All,
    CommandLineInterfaces,
    Visualization,
}

pub enum CommerceDomain {
    Assets,
    Market,
    Sourcing,
    Selling,
    Pricing,
    Negotiation,
    Marketing,
    Trade,
    Buying,
    Support,
    Retail,
}

pub enum SpiritualityDomain {
    Meditation,
    Faith,
    Theology,
    Contemplation,
    Pilgrimage,
    Ritual,
    Worship,
    Asceticism,
    Ethics,
    Mortality,
    Transcendence,
    Wisdom,
    Scripture,
    Prayer,
}

pub enum TravelDomain {
    Logistics,
    Transit,
    Transportation,
    Cycling,
    Migration,
    Driving,
    Destination,
    Tourism,
    Itinerary,
    Navigation,
    Commuting,
}

pub enum WorkDomain {
    Leadership,
    Unemployment,
    Workplace,
    Compensation,
    Vocation,
    Project,
    Freelancing,
    Productivity,
    Teamwork,
    Scheduling,
    JobSearch,
    Career,
    Employment,
    Entrepreneurship,
}

pub enum SoftwareDomain {
    Systems(SystemsLeaf),
    Engineering(EngineeringLeaf),
    Quality(QualityLeaf),
    Distributed(DistributedLeaf),
    Programming(ProgrammingLeaf),
    Operations(OperationsLeaf),
    Theory,
    Security(SecurityLeaf),
    Observability(ObservabilityLeaf),
    Data(DataLeaf),
    Surfaces(SurfacesLeaf),
    Intelligence(IntelligenceLeaf),
}

pub enum SystemsLeaf {
    SystemsProgramming,
    Concurrency,
    All,
}

pub enum HardwareLeaf {
    Networking,
    All,
}

pub struct ScopeSet(Vec<DomainScope>);

pub enum HomeDomain {
    Housing,
    Cleaning,
    Relocation,
    Locksmithing,
    Tidying,
    Renovation,
    Realty,
    Maintenance,
    Utilities,
    Furnishing,
    Appliances,
    Property,
}

pub enum SafetyDomain {
    Cybersecurity,
    Deterrence,
    Privacy,
    Protection,
    Preparedness,
    Disaster,
    Military,
    Risk,
}

pub enum TechnologyDomain {
    Software(SoftwareDomain),
    Hardware(HardwareLeaf),
}

pub enum ProgrammingLeaf {
    Parsing,
    TypeSystems,
    Compilation,
    CodeGeneration,
    All,
    DomainSpecificLanguages,
    Macros,
    Metaprogramming,
    Grammars,
}

pub enum LanguageDomain {
    Rhetoric,
    Grammar,
    Conversation,
    Correspondence,
    Translation,
    Oratory,
    Editing,
    Writing,
    Notation,
    Terminology,
    Listening,
}