// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2Vefc {z2VTcf , z2VcfC ( z2Vetb ,) , z2VQi1 ( z2VSfA ,) , z2Vde5 ( z2VdJT ,) , z2VYYE ( z2VW7d ,) , z2VQvx ( z2Vd44 ,) , z2VN6x ( z2VMFi ,) , z2VZCp ( z2VXTW ,) , z2VRrb ( z2VTbU ,) , z2Vcb2 ( z2Vcwy ,) , z2VYRf ( z2VUUJ ,) , z2VZoY ( z2VZgf ,) , z2VZnN ( z2VacB ,) , z2VSk1 ( z2VUoi ,) , z2Vcsv ( z2VU57 ,) , z2VQsA ( z2VU74 ,) , z2VNdy ( z2VT9a ,) , z2Vaqc ( z2Vefz ,) , z2VP6j ( z2VaNs ,) , z2VZdc ( z2Vdqc ,) , z2VYHB ( z2VRd6 ,) , z2Vd2R ( z2VQsy ,) , z2VVd2 ( z2Vd5x ,) , z2VSih ( z2VX82 ,) , z2VM7z ( z2VYDN ,) ,} 
pub enum z2Vetb {z2VabW , z2VVBk , z2VTRZ , z2VZpN , z2Vcw1 , z2VQ3k , z2Veif , z2VUwF , z2VYsh , z2VMey , z2VRsr , z2VRB9 , z2VRs5 , z2VM7n , z2VStP , z2VQwu , z2VSWF , z2VWrR , z2VW5N , z2VTX3 ,} 
pub enum z2VSfA {z2VcgP , z2VaPA , z2VbRC , z2VWkK , z2VNVH , z2VakR , z2Vbub , z2VS84 , z2VcTW , z2VbLA , z2VPca ,} 
pub enum z2VdJT {z2VSww , z2VLXW , z2VYNH , z2VVNH , z2VaVG , z2VXaT , z2VSNb , z2VTyz , z2Ver7 , z2VZDd , z2VMGX , z2VTZX ,} 
pub enum z2VW7d {z2VM4d , z2VMGv , z2VbE8 , z2VMCE , z2Vbij , z2VPLm , z2VRem , z2VLm6 , z2VYUA , z2VQ8V , z2Vav8 , z2VVxm , z2VWXk , z2VPRx ,} 
pub enum z2Vd44 {z2VZqQ , z2VRxh , z2VbwT , z2VTrV , z2VR9t , z2VX3C , z2Veno , z2VUJW , z2VMqM , z2Vckf , z2VPLf , z2VSGC , z2VUXu , z2VWh9 ,} 
pub enum z2VMFi {z2VUny , z2VM7e , z2VMQV , z2Vb26 , z2VRxV , z2VbMf , z2VQGS , z2VXMc , z2VUdH , z2VPU8 ,} 
pub enum z2VXTW {z2VNQQ , z2VPAe , z2VdKC , z2VWyZ , z2VPgo , z2VTbM , z2VVGg , z2VNsz , z2VRAh , z2VaJL , z2VWe8 , z2VZgJ , z2Vedu , z2VRvf , z2VVPX , z2VdKU , z2VZuy ,} 
pub enum z2VTbU {z2VW9z , z2Vegg , z2VYFj , z2VPZz , z2VLnT , z2Vbju , z2VR5C , z2VaWZ , z2VVuh , z2VQbY ,} 
pub enum z2Vcwy {z2VeBr , z2Vaec , z2VWbM , z2VPfb , z2VSQ7 , z2VdeM , z2VL5a , z2VZtx , z2VeSN , z2VWAQ , z2VaXL ,} 
pub enum z2VUUJ {z2VZQv , z2Vcd7 , z2VQNH , z2Vauf , z2VS8R , z2VXDs , z2VTKZ , z2VTj1 , z2VepU , z2VbJS , z2VZiE , z2VdFc , z2VNm5 ,} 
pub enum z2VZgf {z2VVWB , z2VQVG , z2VcR7 , z2VarY , z2VYBg , z2VPLT , z2VeUD , z2VbhK , z2VVQZ , z2VTAQ , z2VNYi , z2VYkR , z2VeS3 ,} 
pub enum z2VacB {z2VVGM , z2VNVb , z2VS79 , z2VXzn , z2VSMG , z2VPvf , z2VeKN , z2VeLL , z2VYM4 , z2VZWG , z2VSnL , z2VLPS , z2VVXc ,} 
pub enum z2VUoi {z2VTdL , z2VLsE , z2VSFW , z2VaLm , z2VSgv , z2VZPP , z2VYz5 , z2VPjV , z2VazZ , z2VbNU , z2VbHC , z2Vd9L , z2VeCv , z2VaZZ ,} 
pub enum z2VU57 {z2VLk3 , z2VUF5 , z2VVRb , z2VLpy , z2Vbhk , z2VUrn , z2VN2f , z2VUC1 , z2VSze , z2VMde , z2VWWt , z2VP1d , z2VNjU ,} 
pub enum z2VU74 {z2Vbrp , z2VNS9 , z2VPi9 , z2VNfP , z2VT1o , z2VY3c , z2VPt1 , z2VMS6 , z2VaeX , z2VbjV , z2Vb1Q , z2VPsf ,} 
pub enum z2VT9a {z2VNSv , z2VWpn , z2VZFi , z2VWzz , z2VWRt , z2VNED , z2VaeK , z2VPiM , z2VdtK ,} 
pub enum z2Vefz {z2VTmi , z2VS7U , z2VV7f , z2VRTR , z2VTuv , z2VRsL , z2VQUk , z2VeBc , z2VZaf , z2VRtF , z2VYJ4 , z2VdeA , z2VM53 , z2VeQt ,} 
pub enum z2VaNs {z2VNAG , z2VXkE , z2VZLV , z2VUsW , z2VWzL , z2VbQg , z2VLUt , z2Vd8k , z2VbKv , z2VaKh , z2VSse ,} 
pub enum z2Vdqc {z2VTLs , z2VP1E , z2VcaA , z2VYvB , z2VUMF , z2VbEH , z2VRky , z2VSsm , z2VVCZ , z2VQnf , z2VUJg ,} 
pub enum z2VRd6 {z2VRR9 , z2VQGA , z2VZJR , z2VamH , z2VX8i , z2VdNw , z2VZZq , z2VLNt , z2VYGz , z2VSkn , z2VdGF ,} 
pub enum z2VQsy {z2Vc84 , z2VWjD , z2VSAb , z2VUTL , z2VNsL , z2VLng ,} 
pub enum z2Vd5x {z2VNJP , z2VZAD , z2VQ1s , z2Ve64 , z2VTKa , z2VL4x , z2VMLn , z2VQsG ,} 
pub enum z2VX82 {z2VbKH , z2Vb8g , z2VbJo , z2VRxA , z2VSQv , z2VMv9 , z2Vcsy , z2VPA3 , z2VSxH ,} 
pub enum z2VYDN {z2VYvf ( z2VMQR ,) , z2VSAm ( z2VRXn ,) ,} 
pub enum z2VMQR {z2VTRx , z2VWca ,} 
pub enum z2VRXn {z2Vdwx ( z2VNHr ,) , z2VWB4 , z2Vcan ( z2VcT9 ,) , z2Vbie ( z2VPzQ ,) , z2VXQN ( z2VaYC ,) , z2VRSY ( z2VdPi ,) , z2VXMU ( z2VNs2 ,) , z2VdbC ( z2VWfG ,) , z2VQ4o ( z2VXVk ,) , z2VeeD ( z2Vb1K ,) , z2VYxD ( z2VXd9 ,) , z2VNjS ( z2VdTi ,) ,} 
pub enum z2VNHr {z2VdAM , z2VPym , z2VdbW , z2Vb6h , z2VXRn , z2VZhi , z2Vatu , z2VTTb , z2VMvZ ,} 
pub enum z2VcT9 {z2Ve89 , z2Vdwq , z2VaVx ,} 
pub enum z2VPzQ {z2VVRt , z2VQ94 , z2Va4s ,} 
pub enum z2VaYC {z2Vb7s , z2VZQj , z2VM5d , z2VMBn , z2VTor , z2VU5m , z2VQ2Q ,} 
pub enum z2VdPi {z2VcjX , z2VVJ2 ,} 
pub enum z2VNs2 {z2VMKR , z2VLFb , z2VMDN , z2VZQf , z2Vccb , z2VTLE ,} 
pub enum z2VWfG {z2VV74 , z2VcxZ ,} 
pub enum z2VXVk {z2VdB8 , z2VNfK , z2VVBy , z2VZCU , z2VL8v , z2VQSu ,} 
pub enum z2Vb1K {z2VNH6 , z2VWWD ,} 
pub enum z2VXd9 {z2VUuV , z2VPMp , z2VNqY ,} 
pub enum z2VdTi {z2VMmz , z2VUJE , z2VQXh , z2Vdyf , z2VVWF , z2VTJ6 , z2VNEU , z2VUc2 , z2Ve1A ,} 
pub struct z2VNQR(crate::Scope<z2Vefc>);
impl z2VNQR {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: crate::Scope<z2Vefc>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &crate::Scope<z2Vefc> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> crate::Scope<z2Vefc> {
        self.0
    }
}
pub struct z2VZQa(Vec<z2VNQR>);
impl z2VZQa {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VNQR>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VNQR> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VNQR> {
        self.0
    }
}
pub struct z2VUtf(Vec<z2VNQR>);
impl z2VUtf {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VNQR>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VNQR> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VNQR> {
        self.0
    }
}
