//! Shared Signal domain taxonomy contract.
//!
//! `schema/domain.schema` is the source of truth. The checked-in file under
//! `src/schema/` is generated by `schema-rust` and preserved here as a public
//! contract surface without daemon, runtime, storage, or policy behavior.

mod scope;

#[allow(dead_code)]
#[rustfmt::skip]
pub mod schema;

pub use crate::schema::domain::*;
pub use scope::{
    DomainTreeContract, ScopeContainment, ScopeDomainMatching, ScopeFiltering, ScopeOf,
    ScopeOverlap, ScopeTreeContract,
};

/// Compatibility names preserve existing callers while schema source uses
/// distinct payload nouns for Domain's same-named variants.
pub type Health = HealthDomain;
pub type Food = FoodDomain;
pub type Home = HomeDomain;
pub type Finance = FinanceDomain;
pub type Work = WorkDomain;
pub type Craft = CraftDomain;
pub type Knowledge = KnowledgeDomain;
pub type Education = EducationDomain;
pub type Language = LanguageDomain;
pub type Art = ArtDomain;
pub type Kinship = KinshipDomain;
pub type Selfhood = SelfhoodDomain;
pub type Spirituality = SpiritualityDomain;
pub type Governance = GovernanceDomain;
pub type Law = LawDomain;
pub type Community = CommunityDomain;
pub type Nature = NatureDomain;
pub type Travel = TravelDomain;
pub type Commerce = CommerceDomain;
pub type Leisure = LeisureDomain;
pub type Appearance = AppearanceDomain;
pub type Safety = SafetyDomain;
pub type Information = InformationDomain;
pub type Technology = TechnologyDomain;
pub type Software = SoftwareDomain;
pub type HealthScope = HealthDomainScope;
pub type FoodScope = FoodDomainScope;
pub type HomeScope = HomeDomainScope;
pub type FinanceScope = FinanceDomainScope;
pub type WorkScope = WorkDomainScope;
pub type CraftScope = CraftDomainScope;
pub type KnowledgeScope = KnowledgeDomainScope;
pub type EducationScope = EducationDomainScope;
pub type LanguageScope = LanguageDomainScope;
pub type ArtScope = ArtDomainScope;
pub type KinshipScope = KinshipDomainScope;
pub type SelfhoodScope = SelfhoodDomainScope;
pub type SpiritualityScope = SpiritualityDomainScope;
pub type GovernanceScope = GovernanceDomainScope;
pub type LawScope = LawDomainScope;
pub type CommunityScope = CommunityDomainScope;
pub type NatureScope = NatureDomainScope;
pub type TravelScope = TravelDomainScope;
pub type CommerceScope = CommerceDomainScope;
pub type LeisureScope = LeisureDomainScope;
pub type AppearanceScope = AppearanceDomainScope;
pub type SafetyScope = SafetyDomainScope;
pub type InformationScope = InformationDomainScope;
pub type TechnologyScope = TechnologyDomainScope;
pub type SoftwareScope = SoftwareDomainScope;

pub const DOMAIN_SCHEMA_SOURCE: &str = include_str!("../schema/domain.schema");
pub const DOMAIN_RUST_SOURCE: &str = include_str!("schema/domain.rs");

impl Domain {
    // Trait exception — too trivial: compatibility forwarding only.
    pub fn matches_scope(&self, scope: &DomainScope) -> bool {
        <DomainScope as ScopeDomainMatching>::matches_domain(scope, self)
    }

    // Trait exception — too trivial: local variant probe only.
    pub fn is_all(&self) -> bool {
        matches!(self, Self::All)
    }
}

impl DomainScope {
    // Trait exception — too trivial: compatibility forwarding only.
    pub fn matches_domain(&self, domain: &Domain) -> bool {
        <Self as ScopeDomainMatching>::matches_domain(self, domain)
    }

    // Trait exception — too trivial: compatibility forwarding only.
    pub fn matches_scope(&self, scope: &DomainScope) -> bool {
        <Self as ScopeFiltering>::matches_scope(self, scope)
    }

    // Trait exception — too trivial: local variant probe only.
    pub fn is_all(&self) -> bool {
        matches!(self, Self::All)
    }
}

// Trait exception — the proper trait cannot be determined: collection semantics are outside the
// reviewed ScopeOf relation contracts.
impl DomainScopes {
    pub fn iter(&self) -> impl Iterator<Item = &DomainScope> {
        self.payload().iter()
    }

    pub fn matches_any_domain(&self, domains: &[Domain]) -> bool {
        self.iter().any(|scope| {
            domains
                .iter()
                .any(|domain| ScopeDomainMatching::matches_domain(scope, domain))
        })
    }
}

// Trait exception — the proper trait cannot be determined: collection semantics are outside the
// reviewed ScopeOf relation contracts.
impl ScopeSet {
    pub fn iter(&self) -> impl Iterator<Item = &DomainScope> {
        self.payload().iter()
    }

    pub fn matches_domain(&self, domain: &Domain) -> bool {
        self.iter()
            .any(|scope| ScopeDomainMatching::matches_domain(scope, domain))
    }

    pub fn matches_any_domain(&self, domains: &[Domain]) -> bool {
        domains.iter().any(|domain| self.matches_domain(domain))
    }
}
