//! Shared Signal domain taxonomy contract.
//!
//! `schema/domain.schema` is the source of truth. The checked-in file under
//! `src/schema/` is generated by `schema-rust` and preserved here as a public
//! contract surface without daemon, runtime, storage, or policy behavior.

#[allow(dead_code)]
#[rustfmt::skip]
pub mod schema;

pub use crate::schema::domain::*;

pub const DOMAIN_SCHEMA_SOURCE: &str = include_str!("../schema/domain.schema");
pub const DOMAIN_RUST_SOURCE: &str = include_str!("schema/domain.rs");

impl Domain {
    pub fn matches_scope(&self, scope: &DomainScope) -> bool {
        scope.contains_domain(self)
    }
}

impl DomainScope {
    pub fn matches_domain(&self, domain: &Domain) -> bool {
        self.contains_domain(domain)
    }
}

impl DomainScopes {
    pub fn iter(&self) -> impl Iterator<Item = &DomainScope> {
        self.payload().iter()
    }

    pub fn matches_any_domain(&self, domains: &[Domain]) -> bool {
        self.iter()
            .any(|scope| scope.expand().matches_any_domain(domains))
    }
}

impl ScopeSet {
    pub fn iter(&self) -> impl Iterator<Item = &DomainScope> {
        self.payload().iter()
    }

    pub fn matches_domain(&self, domain: &Domain) -> bool {
        self.iter().any(|scope| scope.matches_domain(domain))
    }

    pub fn matches_any_domain(&self, domains: &[Domain]) -> bool {
        domains.iter().any(|domain| self.matches_domain(domain))
    }
}
