// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Domain {
    All,
    Health(HealthDomain),
    Food(FoodDomain),
    Home(HomeDomain),
    Finance(FinanceDomain),
    Work(WorkDomain),
    Craft(CraftDomain),
    Knowledge(KnowledgeDomain),
    Education(EducationDomain),
    Language(LanguageDomain),
    Art(ArtDomain),
    Kinship(KinshipDomain),
    Selfhood(SelfhoodDomain),
    Spirituality(SpiritualityDomain),
    Governance(GovernanceDomain),
    Law(LawDomain),
    Community(CommunityDomain),
    Nature(NatureDomain),
    Travel(TravelDomain),
    Commerce(CommerceDomain),
    Leisure(LeisureDomain),
    Appearance(AppearanceDomain),
    Safety(SafetyDomain),
    Information(InformationDomain),
    Technology(TechnologyDomain),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HealthDomain {
    Body,
    Mind,
    Nutrition,
    Exercise,
    Sleep,
    Medicine,
    Disease,
    Medication,
    Therapy,
    Reproduction,
    Sexuality,
    Aging,
    Disability,
    Addiction,
    Dentistry,
    Senses,
    Pain,
    Prevention,
    FirstAid,
    Rehabilitation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum FoodDomain {
    Cooking,
    Diet,
    Recipe,
    Baking,
    Preservation,
    Fermentation,
    Beverage,
    Entertaining,
    Foraging,
    Fasting,
    Dining,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HomeDomain {
    Housing,
    Maintenance,
    Renovation,
    Furnishing,
    Cleaning,
    Tidying,
    Relocation,
    Realty,
    Property,
    Utilities,
    Locksmithing,
    Appliances,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum FinanceDomain {
    Budgeting,
    Saving,
    Spending,
    Debt,
    Credit,
    Investing,
    Retirement,
    Tax,
    Insurance,
    Income,
    Banking,
    Charity,
    Planning,
    Accounting,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WorkDomain {
    Career,
    JobSearch,
    Workplace,
    Vocation,
    Leadership,
    Entrepreneurship,
    Employment,
    Compensation,
    Scheduling,
    Unemployment,
    Freelancing,
    Teamwork,
    Productivity,
    Project,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CraftDomain {
    Electronics,
    Construction,
    Carpentry,
    Metalworking,
    Sewing,
    Manufacturing,
    Repair,
    Engineering,
    Handicraft,
    Invention,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum KnowledgeDomain {
    Mathematics,
    Logic,
    Physics,
    Chemistry,
    Biology,
    Astronomy,
    Geology,
    Computing,
    Physiology,
    Statistics,
    Research,
    History,
    Linguistics,
    Philosophy,
    Economics,
    Cognition,
    Taxonomy,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EducationDomain {
    Studying,
    Teaching,
    Schooling,
    Skill,
    Reading,
    Memorization,
    Pedagogy,
    Mentoring,
    Autodidacticism,
    Credential,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LanguageDomain {
    Writing,
    Rhetoric,
    Translation,
    Grammar,
    Conversation,
    Correspondence,
    Listening,
    Oratory,
    Editing,
    Terminology,
    Notation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ArtDomain {
    Fiction,
    Poetry,
    Music,
    Painting,
    Photography,
    Film,
    Theater,
    Dance,
    Design,
    Sculpture,
    Creativity,
    Storytelling,
    Publishing,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum KinshipDomain {
    Friendship,
    Romance,
    Marriage,
    Family,
    Parenting,
    Relatives,
    Reconciliation,
    Boundaries,
    Intimacy,
    Rapport,
    Caregiving,
    Grief,
    Belonging,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SelfhoodDomain {
    Growth,
    Introspection,
    Discipline,
    Emotion,
    Virtue,
    Motivation,
    Confidence,
    Identity,
    Purpose,
    Decision,
    Temperament,
    Wellbeing,
    Composure,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SpiritualityDomain {
    Worship,
    Prayer,
    Meditation,
    Ritual,
    Faith,
    Theology,
    Contemplation,
    Pilgrimage,
    Scripture,
    Ethics,
    Mortality,
    Transcendence,
    Asceticism,
    Wisdom,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum GovernanceDomain {
    Politics,
    Government,
    Administration,
    Citizenship,
    Elections,
    Activism,
    Policy,
    Diplomacy,
    Movements,
    Organizing,
    Services,
    Naturalization,
    War,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LawDomain {
    Rights,
    Contract,
    Title,
    Crime,
    Litigation,
    Compliance,
    Custody,
    Liability,
    Procedure,
    Justice,
    Policing,
    Arbitration,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CommunityDomain {
    Neighborliness,
    Volunteering,
    Solidarity,
    Membership,
    Gatherings,
    Reputation,
    Service,
    Hospitality,
    Institutions,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NatureDomain {
    Agriculture,
    Gardening,
    Horticulture,
    Husbandry,
    Pets,
    Forestry,
    Fishing,
    Hunting,
    Conservation,
    Weather,
    Wilderness,
    Sustainability,
    Resources,
    Stewardship,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TravelDomain {
    Itinerary,
    Destination,
    Transportation,
    Driving,
    Navigation,
    Commuting,
    Logistics,
    Migration,
    Tourism,
    Transit,
    Cycling,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CommerceDomain {
    Selling,
    Buying,
    Marketing,
    Retail,
    Sourcing,
    Trade,
    Support,
    Pricing,
    Negotiation,
    Assets,
    Market,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LeisureDomain {
    Recreation,
    Sport,
    Games,
    Hobby,
    Entertainment,
    Collecting,
    Outdoors,
    Play,
    Relaxation,
    Celebration,
    Fandom,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AppearanceDomain {
    Clothing,
    Grooming,
    Style,
    Cosmetics,
    Etiquette,
    Comportment,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SafetyDomain {
    Protection,
    Preparedness,
    Risk,
    Cybersecurity,
    Privacy,
    Disaster,
    Military,
    Deterrence,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InformationDomain {
    Curation,
    RecordKeeping,
    Documentation,
    News,
    Broadcasting,
    Archives,
    Database,
    Retrieval,
    Classification,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TechnologyDomain {
    Hardware(HardwareLeaf),
    Software(SoftwareDomain),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HardwareLeaf {
    All,
    Networking,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SoftwareDomain {
    Programming(ProgrammingLeaf),
    Theory,
    Systems(SystemsLeaf),
    Distributed(DistributedLeaf),
    Data(DataLeaf),
    Intelligence(IntelligenceLeaf),
    Security(SecurityLeaf),
    Quality(QualityLeaf),
    Operations(OperationsLeaf),
    Observability(ObservabilityLeaf),
    Surfaces(SurfacesLeaf),
    Engineering(EngineeringLeaf),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ProgrammingLeaf {
    All,
    TypeSystems,
    Compilation,
    Parsing,
    Grammars,
    CodeGeneration,
    Metaprogramming,
    Macros,
    DomainSpecificLanguages,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SystemsLeaf {
    All,
    SystemsProgramming,
    Concurrency,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DistributedLeaf {
    All,
    ProtocolDesign,
    EventDrivenArchitecture,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DataLeaf {
    All,
    Persistence,
    Serialization,
    Formats,
    Modeling,
    SchemaEvolution,
    Migration,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IntelligenceLeaf {
    All,
    AgentSystems,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SecurityLeaf {
    All,
    Cryptography,
    Authentication,
    Authorization,
    SecretsManagement,
    Privacy,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum QualityLeaf {
    All,
    Testing,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationsLeaf {
    All,
    BuildSystem,
    ReleaseEngineering,
    DependencyManagement,
    Deployment,
    ConfigurationManagement,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObservabilityLeaf {
    All,
    Tracing,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SurfacesLeaf {
    All,
    Visualization,
    CommandLineInterfaces,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EngineeringLeaf {
    All,
    Architecture,
    Design,
    ApplicationProgrammingInterfaces,
    Documentation,
    VersionControl,
    DevelopmentProcess,
    Management,
    Modularity,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DomainScope {
    All,
    Health(HealthDomainScope),
    Food(FoodDomainScope),
    Home(HomeDomainScope),
    Finance(FinanceDomainScope),
    Work(WorkDomainScope),
    Craft(CraftDomainScope),
    Knowledge(KnowledgeDomainScope),
    Education(EducationDomainScope),
    Language(LanguageDomainScope),
    Art(ArtDomainScope),
    Kinship(KinshipDomainScope),
    Selfhood(SelfhoodDomainScope),
    Spirituality(SpiritualityDomainScope),
    Governance(GovernanceDomainScope),
    Law(LawDomainScope),
    Community(CommunityDomainScope),
    Nature(NatureDomainScope),
    Travel(TravelDomainScope),
    Commerce(CommerceDomainScope),
    Leisure(LeisureDomainScope),
    Appearance(AppearanceDomainScope),
    Safety(SafetyDomainScope),
    Information(InformationDomainScope),
    Technology(TechnologyDomainScope),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TechnologyDomainScope {
    All,
    Hardware(HardwareLeafScope),
    Software(SoftwareDomainScope),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SoftwareDomainScope {
    All,
    Programming(ProgrammingLeafScope),
    Theory,
    Systems(SystemsLeafScope),
    Distributed(DistributedLeafScope),
    Data(DataLeafScope),
    Intelligence(IntelligenceLeafScope),
    Security(SecurityLeafScope),
    Quality(QualityLeafScope),
    Operations(OperationsLeafScope),
    Observability(ObservabilityLeafScope),
    Surfaces(SurfacesLeafScope),
    Engineering(EngineeringLeafScope),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EngineeringLeafScope {
    All,
    Architecture,
    Design,
    ApplicationProgrammingInterfaces,
    Documentation,
    VersionControl,
    DevelopmentProcess,
    Management,
    Modularity,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SurfacesLeafScope {
    All,
    Visualization,
    CommandLineInterfaces,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObservabilityLeafScope {
    All,
    Tracing,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OperationsLeafScope {
    All,
    BuildSystem,
    ReleaseEngineering,
    DependencyManagement,
    Deployment,
    ConfigurationManagement,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum QualityLeafScope {
    All,
    Testing,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SecurityLeafScope {
    All,
    Cryptography,
    Authentication,
    Authorization,
    SecretsManagement,
    Privacy,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum IntelligenceLeafScope {
    All,
    AgentSystems,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DataLeafScope {
    All,
    Persistence,
    Serialization,
    Formats,
    Modeling,
    SchemaEvolution,
    Migration,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DistributedLeafScope {
    All,
    ProtocolDesign,
    EventDrivenArchitecture,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SystemsLeafScope {
    All,
    SystemsProgramming,
    Concurrency,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProgrammingLeafScope {
    All,
    TypeSystems,
    Compilation,
    Parsing,
    Grammars,
    CodeGeneration,
    Metaprogramming,
    Macros,
    DomainSpecificLanguages,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HardwareLeafScope {
    All,
    Networking,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum InformationDomainScope {
    All,
    Curation,
    RecordKeeping,
    Documentation,
    News,
    Broadcasting,
    Archives,
    Database,
    Retrieval,
    Classification,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SafetyDomainScope {
    All,
    Protection,
    Preparedness,
    Risk,
    Cybersecurity,
    Privacy,
    Disaster,
    Military,
    Deterrence,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AppearanceDomainScope {
    All,
    Clothing,
    Grooming,
    Style,
    Cosmetics,
    Etiquette,
    Comportment,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LeisureDomainScope {
    All,
    Recreation,
    Sport,
    Games,
    Hobby,
    Entertainment,
    Collecting,
    Outdoors,
    Play,
    Relaxation,
    Celebration,
    Fandom,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CommerceDomainScope {
    All,
    Selling,
    Buying,
    Marketing,
    Retail,
    Sourcing,
    Trade,
    Support,
    Pricing,
    Negotiation,
    Assets,
    Market,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TravelDomainScope {
    All,
    Itinerary,
    Destination,
    Transportation,
    Driving,
    Navigation,
    Commuting,
    Logistics,
    Migration,
    Tourism,
    Transit,
    Cycling,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NatureDomainScope {
    All,
    Agriculture,
    Gardening,
    Horticulture,
    Husbandry,
    Pets,
    Forestry,
    Fishing,
    Hunting,
    Conservation,
    Weather,
    Wilderness,
    Sustainability,
    Resources,
    Stewardship,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CommunityDomainScope {
    All,
    Neighborliness,
    Volunteering,
    Solidarity,
    Membership,
    Gatherings,
    Reputation,
    Service,
    Hospitality,
    Institutions,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LawDomainScope {
    All,
    Rights,
    Contract,
    Title,
    Crime,
    Litigation,
    Compliance,
    Custody,
    Liability,
    Procedure,
    Justice,
    Policing,
    Arbitration,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum GovernanceDomainScope {
    All,
    Politics,
    Government,
    Administration,
    Citizenship,
    Elections,
    Activism,
    Policy,
    Diplomacy,
    Movements,
    Organizing,
    Services,
    Naturalization,
    War,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SpiritualityDomainScope {
    All,
    Worship,
    Prayer,
    Meditation,
    Ritual,
    Faith,
    Theology,
    Contemplation,
    Pilgrimage,
    Scripture,
    Ethics,
    Mortality,
    Transcendence,
    Asceticism,
    Wisdom,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SelfhoodDomainScope {
    All,
    Growth,
    Introspection,
    Discipline,
    Emotion,
    Virtue,
    Motivation,
    Confidence,
    Identity,
    Purpose,
    Decision,
    Temperament,
    Wellbeing,
    Composure,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum KinshipDomainScope {
    All,
    Friendship,
    Romance,
    Marriage,
    Family,
    Parenting,
    Relatives,
    Reconciliation,
    Boundaries,
    Intimacy,
    Rapport,
    Caregiving,
    Grief,
    Belonging,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ArtDomainScope {
    All,
    Fiction,
    Poetry,
    Music,
    Painting,
    Photography,
    Film,
    Theater,
    Dance,
    Design,
    Sculpture,
    Creativity,
    Storytelling,
    Publishing,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LanguageDomainScope {
    All,
    Writing,
    Rhetoric,
    Translation,
    Grammar,
    Conversation,
    Correspondence,
    Listening,
    Oratory,
    Editing,
    Terminology,
    Notation,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EducationDomainScope {
    All,
    Studying,
    Teaching,
    Schooling,
    Skill,
    Reading,
    Memorization,
    Pedagogy,
    Mentoring,
    Autodidacticism,
    Credential,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum KnowledgeDomainScope {
    All,
    Mathematics,
    Logic,
    Physics,
    Chemistry,
    Biology,
    Astronomy,
    Geology,
    Computing,
    Physiology,
    Statistics,
    Research,
    History,
    Linguistics,
    Philosophy,
    Economics,
    Cognition,
    Taxonomy,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CraftDomainScope {
    All,
    Electronics,
    Construction,
    Carpentry,
    Metalworking,
    Sewing,
    Manufacturing,
    Repair,
    Engineering,
    Handicraft,
    Invention,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WorkDomainScope {
    All,
    Career,
    JobSearch,
    Workplace,
    Vocation,
    Leadership,
    Entrepreneurship,
    Employment,
    Compensation,
    Scheduling,
    Unemployment,
    Freelancing,
    Teamwork,
    Productivity,
    Project,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum FinanceDomainScope {
    All,
    Budgeting,
    Saving,
    Spending,
    Debt,
    Credit,
    Investing,
    Retirement,
    Tax,
    Insurance,
    Income,
    Banking,
    Charity,
    Planning,
    Accounting,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HomeDomainScope {
    All,
    Housing,
    Maintenance,
    Renovation,
    Furnishing,
    Cleaning,
    Tidying,
    Relocation,
    Realty,
    Property,
    Utilities,
    Locksmithing,
    Appliances,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum FoodDomainScope {
    All,
    Cooking,
    Diet,
    Recipe,
    Baking,
    Preservation,
    Fermentation,
    Beverage,
    Entertaining,
    Foraging,
    Fasting,
    Dining,
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HealthDomainScope {
    All,
    Body,
    Mind,
    Nutrition,
    Exercise,
    Sleep,
    Medicine,
    Disease,
    Medication,
    Therapy,
    Reproduction,
    Sexuality,
    Aging,
    Disability,
    Addiction,
    Dentistry,
    Senses,
    Pain,
    Prevention,
    FirstAid,
    Rehabilitation,
}
#[rustfmt::skip]
impl From<HealthDomain> for HealthDomainScope {
    fn from(value: HealthDomain) -> Self {
        match value {
            HealthDomain::Body => Self::Body,
            HealthDomain::Mind => Self::Mind,
            HealthDomain::Nutrition => Self::Nutrition,
            HealthDomain::Exercise => Self::Exercise,
            HealthDomain::Sleep => Self::Sleep,
            HealthDomain::Medicine => Self::Medicine,
            HealthDomain::Disease => Self::Disease,
            HealthDomain::Medication => Self::Medication,
            HealthDomain::Therapy => Self::Therapy,
            HealthDomain::Reproduction => Self::Reproduction,
            HealthDomain::Sexuality => Self::Sexuality,
            HealthDomain::Aging => Self::Aging,
            HealthDomain::Disability => Self::Disability,
            HealthDomain::Addiction => Self::Addiction,
            HealthDomain::Dentistry => Self::Dentistry,
            HealthDomain::Senses => Self::Senses,
            HealthDomain::Pain => Self::Pain,
            HealthDomain::Prevention => Self::Prevention,
            HealthDomain::FirstAid => Self::FirstAid,
            HealthDomain::Rehabilitation => Self::Rehabilitation,
        }
    }
}
#[rustfmt::skip]
impl HealthDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Body, Self::Body) | (Self::Mind,
            Self::Mind) | (Self::Nutrition, Self::Nutrition) | (Self::Exercise,
            Self::Exercise) | (Self::Sleep, Self::Sleep) | (Self::Medicine,
            Self::Medicine) | (Self::Disease, Self::Disease) | (Self::Medication,
            Self::Medication) | (Self::Therapy, Self::Therapy) | (Self::Reproduction,
            Self::Reproduction) | (Self::Sexuality, Self::Sexuality) | (Self::Aging,
            Self::Aging) | (Self::Disability, Self::Disability) | (Self::Addiction,
            Self::Addiction) | (Self::Dentistry, Self::Dentistry) | (Self::Senses,
            Self::Senses) | (Self::Pain, Self::Pain) | (Self::Prevention,
            Self::Prevention) | (Self::FirstAid, Self::FirstAid) | (Self::Rehabilitation,
            Self::Rehabilitation)
        )
    }
}
#[rustfmt::skip]
impl From<FoodDomain> for FoodDomainScope {
    fn from(value: FoodDomain) -> Self {
        match value {
            FoodDomain::Cooking => Self::Cooking,
            FoodDomain::Diet => Self::Diet,
            FoodDomain::Recipe => Self::Recipe,
            FoodDomain::Baking => Self::Baking,
            FoodDomain::Preservation => Self::Preservation,
            FoodDomain::Fermentation => Self::Fermentation,
            FoodDomain::Beverage => Self::Beverage,
            FoodDomain::Entertaining => Self::Entertaining,
            FoodDomain::Foraging => Self::Foraging,
            FoodDomain::Fasting => Self::Fasting,
            FoodDomain::Dining => Self::Dining,
        }
    }
}
#[rustfmt::skip]
impl FoodDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Cooking, Self::Cooking) | (Self::Diet,
            Self::Diet) | (Self::Recipe, Self::Recipe) | (Self::Baking, Self::Baking) |
            (Self::Preservation, Self::Preservation) | (Self::Fermentation,
            Self::Fermentation) | (Self::Beverage, Self::Beverage) | (Self::Entertaining,
            Self::Entertaining) | (Self::Foraging, Self::Foraging) | (Self::Fasting,
            Self::Fasting) | (Self::Dining, Self::Dining)
        )
    }
}
#[rustfmt::skip]
impl From<HomeDomain> for HomeDomainScope {
    fn from(value: HomeDomain) -> Self {
        match value {
            HomeDomain::Housing => Self::Housing,
            HomeDomain::Maintenance => Self::Maintenance,
            HomeDomain::Renovation => Self::Renovation,
            HomeDomain::Furnishing => Self::Furnishing,
            HomeDomain::Cleaning => Self::Cleaning,
            HomeDomain::Tidying => Self::Tidying,
            HomeDomain::Relocation => Self::Relocation,
            HomeDomain::Realty => Self::Realty,
            HomeDomain::Property => Self::Property,
            HomeDomain::Utilities => Self::Utilities,
            HomeDomain::Locksmithing => Self::Locksmithing,
            HomeDomain::Appliances => Self::Appliances,
        }
    }
}
#[rustfmt::skip]
impl HomeDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Housing, Self::Housing) |
            (Self::Maintenance, Self::Maintenance) | (Self::Renovation, Self::Renovation)
            | (Self::Furnishing, Self::Furnishing) | (Self::Cleaning, Self::Cleaning) |
            (Self::Tidying, Self::Tidying) | (Self::Relocation, Self::Relocation) |
            (Self::Realty, Self::Realty) | (Self::Property, Self::Property) |
            (Self::Utilities, Self::Utilities) | (Self::Locksmithing, Self::Locksmithing)
            | (Self::Appliances, Self::Appliances)
        )
    }
}
#[rustfmt::skip]
impl From<FinanceDomain> for FinanceDomainScope {
    fn from(value: FinanceDomain) -> Self {
        match value {
            FinanceDomain::Budgeting => Self::Budgeting,
            FinanceDomain::Saving => Self::Saving,
            FinanceDomain::Spending => Self::Spending,
            FinanceDomain::Debt => Self::Debt,
            FinanceDomain::Credit => Self::Credit,
            FinanceDomain::Investing => Self::Investing,
            FinanceDomain::Retirement => Self::Retirement,
            FinanceDomain::Tax => Self::Tax,
            FinanceDomain::Insurance => Self::Insurance,
            FinanceDomain::Income => Self::Income,
            FinanceDomain::Banking => Self::Banking,
            FinanceDomain::Charity => Self::Charity,
            FinanceDomain::Planning => Self::Planning,
            FinanceDomain::Accounting => Self::Accounting,
        }
    }
}
#[rustfmt::skip]
impl FinanceDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Budgeting, Self::Budgeting) |
            (Self::Saving, Self::Saving) | (Self::Spending, Self::Spending) |
            (Self::Debt, Self::Debt) | (Self::Credit, Self::Credit) | (Self::Investing,
            Self::Investing) | (Self::Retirement, Self::Retirement) | (Self::Tax,
            Self::Tax) | (Self::Insurance, Self::Insurance) | (Self::Income,
            Self::Income) | (Self::Banking, Self::Banking) | (Self::Charity,
            Self::Charity) | (Self::Planning, Self::Planning) | (Self::Accounting,
            Self::Accounting)
        )
    }
}
#[rustfmt::skip]
impl From<WorkDomain> for WorkDomainScope {
    fn from(value: WorkDomain) -> Self {
        match value {
            WorkDomain::Career => Self::Career,
            WorkDomain::JobSearch => Self::JobSearch,
            WorkDomain::Workplace => Self::Workplace,
            WorkDomain::Vocation => Self::Vocation,
            WorkDomain::Leadership => Self::Leadership,
            WorkDomain::Entrepreneurship => Self::Entrepreneurship,
            WorkDomain::Employment => Self::Employment,
            WorkDomain::Compensation => Self::Compensation,
            WorkDomain::Scheduling => Self::Scheduling,
            WorkDomain::Unemployment => Self::Unemployment,
            WorkDomain::Freelancing => Self::Freelancing,
            WorkDomain::Teamwork => Self::Teamwork,
            WorkDomain::Productivity => Self::Productivity,
            WorkDomain::Project => Self::Project,
        }
    }
}
#[rustfmt::skip]
impl WorkDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Career, Self::Career) |
            (Self::JobSearch, Self::JobSearch) | (Self::Workplace, Self::Workplace) |
            (Self::Vocation, Self::Vocation) | (Self::Leadership, Self::Leadership) |
            (Self::Entrepreneurship, Self::Entrepreneurship) | (Self::Employment,
            Self::Employment) | (Self::Compensation, Self::Compensation) |
            (Self::Scheduling, Self::Scheduling) | (Self::Unemployment,
            Self::Unemployment) | (Self::Freelancing, Self::Freelancing) |
            (Self::Teamwork, Self::Teamwork) | (Self::Productivity, Self::Productivity) |
            (Self::Project, Self::Project)
        )
    }
}
#[rustfmt::skip]
impl From<CraftDomain> for CraftDomainScope {
    fn from(value: CraftDomain) -> Self {
        match value {
            CraftDomain::Electronics => Self::Electronics,
            CraftDomain::Construction => Self::Construction,
            CraftDomain::Carpentry => Self::Carpentry,
            CraftDomain::Metalworking => Self::Metalworking,
            CraftDomain::Sewing => Self::Sewing,
            CraftDomain::Manufacturing => Self::Manufacturing,
            CraftDomain::Repair => Self::Repair,
            CraftDomain::Engineering => Self::Engineering,
            CraftDomain::Handicraft => Self::Handicraft,
            CraftDomain::Invention => Self::Invention,
        }
    }
}
#[rustfmt::skip]
impl CraftDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Electronics, Self::Electronics) |
            (Self::Construction, Self::Construction) | (Self::Carpentry, Self::Carpentry)
            | (Self::Metalworking, Self::Metalworking) | (Self::Sewing, Self::Sewing) |
            (Self::Manufacturing, Self::Manufacturing) | (Self::Repair, Self::Repair) |
            (Self::Engineering, Self::Engineering) | (Self::Handicraft, Self::Handicraft)
            | (Self::Invention, Self::Invention)
        )
    }
}
#[rustfmt::skip]
impl From<KnowledgeDomain> for KnowledgeDomainScope {
    fn from(value: KnowledgeDomain) -> Self {
        match value {
            KnowledgeDomain::Mathematics => Self::Mathematics,
            KnowledgeDomain::Logic => Self::Logic,
            KnowledgeDomain::Physics => Self::Physics,
            KnowledgeDomain::Chemistry => Self::Chemistry,
            KnowledgeDomain::Biology => Self::Biology,
            KnowledgeDomain::Astronomy => Self::Astronomy,
            KnowledgeDomain::Geology => Self::Geology,
            KnowledgeDomain::Computing => Self::Computing,
            KnowledgeDomain::Physiology => Self::Physiology,
            KnowledgeDomain::Statistics => Self::Statistics,
            KnowledgeDomain::Research => Self::Research,
            KnowledgeDomain::History => Self::History,
            KnowledgeDomain::Linguistics => Self::Linguistics,
            KnowledgeDomain::Philosophy => Self::Philosophy,
            KnowledgeDomain::Economics => Self::Economics,
            KnowledgeDomain::Cognition => Self::Cognition,
            KnowledgeDomain::Taxonomy => Self::Taxonomy,
        }
    }
}
#[rustfmt::skip]
impl KnowledgeDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Mathematics, Self::Mathematics) |
            (Self::Logic, Self::Logic) | (Self::Physics, Self::Physics) |
            (Self::Chemistry, Self::Chemistry) | (Self::Biology, Self::Biology) |
            (Self::Astronomy, Self::Astronomy) | (Self::Geology, Self::Geology) |
            (Self::Computing, Self::Computing) | (Self::Physiology, Self::Physiology) |
            (Self::Statistics, Self::Statistics) | (Self::Research, Self::Research) |
            (Self::History, Self::History) | (Self::Linguistics, Self::Linguistics) |
            (Self::Philosophy, Self::Philosophy) | (Self::Economics, Self::Economics) |
            (Self::Cognition, Self::Cognition) | (Self::Taxonomy, Self::Taxonomy)
        )
    }
}
#[rustfmt::skip]
impl From<EducationDomain> for EducationDomainScope {
    fn from(value: EducationDomain) -> Self {
        match value {
            EducationDomain::Studying => Self::Studying,
            EducationDomain::Teaching => Self::Teaching,
            EducationDomain::Schooling => Self::Schooling,
            EducationDomain::Skill => Self::Skill,
            EducationDomain::Reading => Self::Reading,
            EducationDomain::Memorization => Self::Memorization,
            EducationDomain::Pedagogy => Self::Pedagogy,
            EducationDomain::Mentoring => Self::Mentoring,
            EducationDomain::Autodidacticism => Self::Autodidacticism,
            EducationDomain::Credential => Self::Credential,
        }
    }
}
#[rustfmt::skip]
impl EducationDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Studying, Self::Studying) |
            (Self::Teaching, Self::Teaching) | (Self::Schooling, Self::Schooling) |
            (Self::Skill, Self::Skill) | (Self::Reading, Self::Reading) |
            (Self::Memorization, Self::Memorization) | (Self::Pedagogy, Self::Pedagogy) |
            (Self::Mentoring, Self::Mentoring) | (Self::Autodidacticism,
            Self::Autodidacticism) | (Self::Credential, Self::Credential)
        )
    }
}
#[rustfmt::skip]
impl From<LanguageDomain> for LanguageDomainScope {
    fn from(value: LanguageDomain) -> Self {
        match value {
            LanguageDomain::Writing => Self::Writing,
            LanguageDomain::Rhetoric => Self::Rhetoric,
            LanguageDomain::Translation => Self::Translation,
            LanguageDomain::Grammar => Self::Grammar,
            LanguageDomain::Conversation => Self::Conversation,
            LanguageDomain::Correspondence => Self::Correspondence,
            LanguageDomain::Listening => Self::Listening,
            LanguageDomain::Oratory => Self::Oratory,
            LanguageDomain::Editing => Self::Editing,
            LanguageDomain::Terminology => Self::Terminology,
            LanguageDomain::Notation => Self::Notation,
        }
    }
}
#[rustfmt::skip]
impl LanguageDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Writing, Self::Writing) |
            (Self::Rhetoric, Self::Rhetoric) | (Self::Translation, Self::Translation) |
            (Self::Grammar, Self::Grammar) | (Self::Conversation, Self::Conversation) |
            (Self::Correspondence, Self::Correspondence) | (Self::Listening,
            Self::Listening) | (Self::Oratory, Self::Oratory) | (Self::Editing,
            Self::Editing) | (Self::Terminology, Self::Terminology) | (Self::Notation,
            Self::Notation)
        )
    }
}
#[rustfmt::skip]
impl From<ArtDomain> for ArtDomainScope {
    fn from(value: ArtDomain) -> Self {
        match value {
            ArtDomain::Fiction => Self::Fiction,
            ArtDomain::Poetry => Self::Poetry,
            ArtDomain::Music => Self::Music,
            ArtDomain::Painting => Self::Painting,
            ArtDomain::Photography => Self::Photography,
            ArtDomain::Film => Self::Film,
            ArtDomain::Theater => Self::Theater,
            ArtDomain::Dance => Self::Dance,
            ArtDomain::Design => Self::Design,
            ArtDomain::Sculpture => Self::Sculpture,
            ArtDomain::Creativity => Self::Creativity,
            ArtDomain::Storytelling => Self::Storytelling,
            ArtDomain::Publishing => Self::Publishing,
        }
    }
}
#[rustfmt::skip]
impl ArtDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Fiction, Self::Fiction) |
            (Self::Poetry, Self::Poetry) | (Self::Music, Self::Music) | (Self::Painting,
            Self::Painting) | (Self::Photography, Self::Photography) | (Self::Film,
            Self::Film) | (Self::Theater, Self::Theater) | (Self::Dance, Self::Dance) |
            (Self::Design, Self::Design) | (Self::Sculpture, Self::Sculpture) |
            (Self::Creativity, Self::Creativity) | (Self::Storytelling,
            Self::Storytelling) | (Self::Publishing, Self::Publishing)
        )
    }
}
#[rustfmt::skip]
impl From<KinshipDomain> for KinshipDomainScope {
    fn from(value: KinshipDomain) -> Self {
        match value {
            KinshipDomain::Friendship => Self::Friendship,
            KinshipDomain::Romance => Self::Romance,
            KinshipDomain::Marriage => Self::Marriage,
            KinshipDomain::Family => Self::Family,
            KinshipDomain::Parenting => Self::Parenting,
            KinshipDomain::Relatives => Self::Relatives,
            KinshipDomain::Reconciliation => Self::Reconciliation,
            KinshipDomain::Boundaries => Self::Boundaries,
            KinshipDomain::Intimacy => Self::Intimacy,
            KinshipDomain::Rapport => Self::Rapport,
            KinshipDomain::Caregiving => Self::Caregiving,
            KinshipDomain::Grief => Self::Grief,
            KinshipDomain::Belonging => Self::Belonging,
        }
    }
}
#[rustfmt::skip]
impl KinshipDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Friendship, Self::Friendship) |
            (Self::Romance, Self::Romance) | (Self::Marriage, Self::Marriage) |
            (Self::Family, Self::Family) | (Self::Parenting, Self::Parenting) |
            (Self::Relatives, Self::Relatives) | (Self::Reconciliation,
            Self::Reconciliation) | (Self::Boundaries, Self::Boundaries) |
            (Self::Intimacy, Self::Intimacy) | (Self::Rapport, Self::Rapport) |
            (Self::Caregiving, Self::Caregiving) | (Self::Grief, Self::Grief) |
            (Self::Belonging, Self::Belonging)
        )
    }
}
#[rustfmt::skip]
impl From<SelfhoodDomain> for SelfhoodDomainScope {
    fn from(value: SelfhoodDomain) -> Self {
        match value {
            SelfhoodDomain::Growth => Self::Growth,
            SelfhoodDomain::Introspection => Self::Introspection,
            SelfhoodDomain::Discipline => Self::Discipline,
            SelfhoodDomain::Emotion => Self::Emotion,
            SelfhoodDomain::Virtue => Self::Virtue,
            SelfhoodDomain::Motivation => Self::Motivation,
            SelfhoodDomain::Confidence => Self::Confidence,
            SelfhoodDomain::Identity => Self::Identity,
            SelfhoodDomain::Purpose => Self::Purpose,
            SelfhoodDomain::Decision => Self::Decision,
            SelfhoodDomain::Temperament => Self::Temperament,
            SelfhoodDomain::Wellbeing => Self::Wellbeing,
            SelfhoodDomain::Composure => Self::Composure,
        }
    }
}
#[rustfmt::skip]
impl SelfhoodDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Growth, Self::Growth) |
            (Self::Introspection, Self::Introspection) | (Self::Discipline,
            Self::Discipline) | (Self::Emotion, Self::Emotion) | (Self::Virtue,
            Self::Virtue) | (Self::Motivation, Self::Motivation) | (Self::Confidence,
            Self::Confidence) | (Self::Identity, Self::Identity) | (Self::Purpose,
            Self::Purpose) | (Self::Decision, Self::Decision) | (Self::Temperament,
            Self::Temperament) | (Self::Wellbeing, Self::Wellbeing) | (Self::Composure,
            Self::Composure)
        )
    }
}
#[rustfmt::skip]
impl From<SpiritualityDomain> for SpiritualityDomainScope {
    fn from(value: SpiritualityDomain) -> Self {
        match value {
            SpiritualityDomain::Worship => Self::Worship,
            SpiritualityDomain::Prayer => Self::Prayer,
            SpiritualityDomain::Meditation => Self::Meditation,
            SpiritualityDomain::Ritual => Self::Ritual,
            SpiritualityDomain::Faith => Self::Faith,
            SpiritualityDomain::Theology => Self::Theology,
            SpiritualityDomain::Contemplation => Self::Contemplation,
            SpiritualityDomain::Pilgrimage => Self::Pilgrimage,
            SpiritualityDomain::Scripture => Self::Scripture,
            SpiritualityDomain::Ethics => Self::Ethics,
            SpiritualityDomain::Mortality => Self::Mortality,
            SpiritualityDomain::Transcendence => Self::Transcendence,
            SpiritualityDomain::Asceticism => Self::Asceticism,
            SpiritualityDomain::Wisdom => Self::Wisdom,
        }
    }
}
#[rustfmt::skip]
impl SpiritualityDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Worship, Self::Worship) |
            (Self::Prayer, Self::Prayer) | (Self::Meditation, Self::Meditation) |
            (Self::Ritual, Self::Ritual) | (Self::Faith, Self::Faith) | (Self::Theology,
            Self::Theology) | (Self::Contemplation, Self::Contemplation) |
            (Self::Pilgrimage, Self::Pilgrimage) | (Self::Scripture, Self::Scripture) |
            (Self::Ethics, Self::Ethics) | (Self::Mortality, Self::Mortality) |
            (Self::Transcendence, Self::Transcendence) | (Self::Asceticism,
            Self::Asceticism) | (Self::Wisdom, Self::Wisdom)
        )
    }
}
#[rustfmt::skip]
impl From<GovernanceDomain> for GovernanceDomainScope {
    fn from(value: GovernanceDomain) -> Self {
        match value {
            GovernanceDomain::Politics => Self::Politics,
            GovernanceDomain::Government => Self::Government,
            GovernanceDomain::Administration => Self::Administration,
            GovernanceDomain::Citizenship => Self::Citizenship,
            GovernanceDomain::Elections => Self::Elections,
            GovernanceDomain::Activism => Self::Activism,
            GovernanceDomain::Policy => Self::Policy,
            GovernanceDomain::Diplomacy => Self::Diplomacy,
            GovernanceDomain::Movements => Self::Movements,
            GovernanceDomain::Organizing => Self::Organizing,
            GovernanceDomain::Services => Self::Services,
            GovernanceDomain::Naturalization => Self::Naturalization,
            GovernanceDomain::War => Self::War,
        }
    }
}
#[rustfmt::skip]
impl GovernanceDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Politics, Self::Politics) |
            (Self::Government, Self::Government) | (Self::Administration,
            Self::Administration) | (Self::Citizenship, Self::Citizenship) |
            (Self::Elections, Self::Elections) | (Self::Activism, Self::Activism) |
            (Self::Policy, Self::Policy) | (Self::Diplomacy, Self::Diplomacy) |
            (Self::Movements, Self::Movements) | (Self::Organizing, Self::Organizing) |
            (Self::Services, Self::Services) | (Self::Naturalization,
            Self::Naturalization) | (Self::War, Self::War)
        )
    }
}
#[rustfmt::skip]
impl From<LawDomain> for LawDomainScope {
    fn from(value: LawDomain) -> Self {
        match value {
            LawDomain::Rights => Self::Rights,
            LawDomain::Contract => Self::Contract,
            LawDomain::Title => Self::Title,
            LawDomain::Crime => Self::Crime,
            LawDomain::Litigation => Self::Litigation,
            LawDomain::Compliance => Self::Compliance,
            LawDomain::Custody => Self::Custody,
            LawDomain::Liability => Self::Liability,
            LawDomain::Procedure => Self::Procedure,
            LawDomain::Justice => Self::Justice,
            LawDomain::Policing => Self::Policing,
            LawDomain::Arbitration => Self::Arbitration,
        }
    }
}
#[rustfmt::skip]
impl LawDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Rights, Self::Rights) |
            (Self::Contract, Self::Contract) | (Self::Title, Self::Title) | (Self::Crime,
            Self::Crime) | (Self::Litigation, Self::Litigation) | (Self::Compliance,
            Self::Compliance) | (Self::Custody, Self::Custody) | (Self::Liability,
            Self::Liability) | (Self::Procedure, Self::Procedure) | (Self::Justice,
            Self::Justice) | (Self::Policing, Self::Policing) | (Self::Arbitration,
            Self::Arbitration)
        )
    }
}
#[rustfmt::skip]
impl From<CommunityDomain> for CommunityDomainScope {
    fn from(value: CommunityDomain) -> Self {
        match value {
            CommunityDomain::Neighborliness => Self::Neighborliness,
            CommunityDomain::Volunteering => Self::Volunteering,
            CommunityDomain::Solidarity => Self::Solidarity,
            CommunityDomain::Membership => Self::Membership,
            CommunityDomain::Gatherings => Self::Gatherings,
            CommunityDomain::Reputation => Self::Reputation,
            CommunityDomain::Service => Self::Service,
            CommunityDomain::Hospitality => Self::Hospitality,
            CommunityDomain::Institutions => Self::Institutions,
        }
    }
}
#[rustfmt::skip]
impl CommunityDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Neighborliness, Self::Neighborliness)
            | (Self::Volunteering, Self::Volunteering) | (Self::Solidarity,
            Self::Solidarity) | (Self::Membership, Self::Membership) | (Self::Gatherings,
            Self::Gatherings) | (Self::Reputation, Self::Reputation) | (Self::Service,
            Self::Service) | (Self::Hospitality, Self::Hospitality) |
            (Self::Institutions, Self::Institutions)
        )
    }
}
#[rustfmt::skip]
impl From<NatureDomain> for NatureDomainScope {
    fn from(value: NatureDomain) -> Self {
        match value {
            NatureDomain::Agriculture => Self::Agriculture,
            NatureDomain::Gardening => Self::Gardening,
            NatureDomain::Horticulture => Self::Horticulture,
            NatureDomain::Husbandry => Self::Husbandry,
            NatureDomain::Pets => Self::Pets,
            NatureDomain::Forestry => Self::Forestry,
            NatureDomain::Fishing => Self::Fishing,
            NatureDomain::Hunting => Self::Hunting,
            NatureDomain::Conservation => Self::Conservation,
            NatureDomain::Weather => Self::Weather,
            NatureDomain::Wilderness => Self::Wilderness,
            NatureDomain::Sustainability => Self::Sustainability,
            NatureDomain::Resources => Self::Resources,
            NatureDomain::Stewardship => Self::Stewardship,
        }
    }
}
#[rustfmt::skip]
impl NatureDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Agriculture, Self::Agriculture) |
            (Self::Gardening, Self::Gardening) | (Self::Horticulture, Self::Horticulture)
            | (Self::Husbandry, Self::Husbandry) | (Self::Pets, Self::Pets) |
            (Self::Forestry, Self::Forestry) | (Self::Fishing, Self::Fishing) |
            (Self::Hunting, Self::Hunting) | (Self::Conservation, Self::Conservation) |
            (Self::Weather, Self::Weather) | (Self::Wilderness, Self::Wilderness) |
            (Self::Sustainability, Self::Sustainability) | (Self::Resources,
            Self::Resources) | (Self::Stewardship, Self::Stewardship)
        )
    }
}
#[rustfmt::skip]
impl From<TravelDomain> for TravelDomainScope {
    fn from(value: TravelDomain) -> Self {
        match value {
            TravelDomain::Itinerary => Self::Itinerary,
            TravelDomain::Destination => Self::Destination,
            TravelDomain::Transportation => Self::Transportation,
            TravelDomain::Driving => Self::Driving,
            TravelDomain::Navigation => Self::Navigation,
            TravelDomain::Commuting => Self::Commuting,
            TravelDomain::Logistics => Self::Logistics,
            TravelDomain::Migration => Self::Migration,
            TravelDomain::Tourism => Self::Tourism,
            TravelDomain::Transit => Self::Transit,
            TravelDomain::Cycling => Self::Cycling,
        }
    }
}
#[rustfmt::skip]
impl TravelDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Itinerary, Self::Itinerary) |
            (Self::Destination, Self::Destination) | (Self::Transportation,
            Self::Transportation) | (Self::Driving, Self::Driving) | (Self::Navigation,
            Self::Navigation) | (Self::Commuting, Self::Commuting) | (Self::Logistics,
            Self::Logistics) | (Self::Migration, Self::Migration) | (Self::Tourism,
            Self::Tourism) | (Self::Transit, Self::Transit) | (Self::Cycling,
            Self::Cycling)
        )
    }
}
#[rustfmt::skip]
impl From<CommerceDomain> for CommerceDomainScope {
    fn from(value: CommerceDomain) -> Self {
        match value {
            CommerceDomain::Selling => Self::Selling,
            CommerceDomain::Buying => Self::Buying,
            CommerceDomain::Marketing => Self::Marketing,
            CommerceDomain::Retail => Self::Retail,
            CommerceDomain::Sourcing => Self::Sourcing,
            CommerceDomain::Trade => Self::Trade,
            CommerceDomain::Support => Self::Support,
            CommerceDomain::Pricing => Self::Pricing,
            CommerceDomain::Negotiation => Self::Negotiation,
            CommerceDomain::Assets => Self::Assets,
            CommerceDomain::Market => Self::Market,
        }
    }
}
#[rustfmt::skip]
impl CommerceDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Selling, Self::Selling) |
            (Self::Buying, Self::Buying) | (Self::Marketing, Self::Marketing) |
            (Self::Retail, Self::Retail) | (Self::Sourcing, Self::Sourcing) |
            (Self::Trade, Self::Trade) | (Self::Support, Self::Support) | (Self::Pricing,
            Self::Pricing) | (Self::Negotiation, Self::Negotiation) | (Self::Assets,
            Self::Assets) | (Self::Market, Self::Market)
        )
    }
}
#[rustfmt::skip]
impl From<LeisureDomain> for LeisureDomainScope {
    fn from(value: LeisureDomain) -> Self {
        match value {
            LeisureDomain::Recreation => Self::Recreation,
            LeisureDomain::Sport => Self::Sport,
            LeisureDomain::Games => Self::Games,
            LeisureDomain::Hobby => Self::Hobby,
            LeisureDomain::Entertainment => Self::Entertainment,
            LeisureDomain::Collecting => Self::Collecting,
            LeisureDomain::Outdoors => Self::Outdoors,
            LeisureDomain::Play => Self::Play,
            LeisureDomain::Relaxation => Self::Relaxation,
            LeisureDomain::Celebration => Self::Celebration,
            LeisureDomain::Fandom => Self::Fandom,
        }
    }
}
#[rustfmt::skip]
impl LeisureDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Recreation, Self::Recreation) |
            (Self::Sport, Self::Sport) | (Self::Games, Self::Games) | (Self::Hobby,
            Self::Hobby) | (Self::Entertainment, Self::Entertainment) |
            (Self::Collecting, Self::Collecting) | (Self::Outdoors, Self::Outdoors) |
            (Self::Play, Self::Play) | (Self::Relaxation, Self::Relaxation) |
            (Self::Celebration, Self::Celebration) | (Self::Fandom, Self::Fandom)
        )
    }
}
#[rustfmt::skip]
impl From<AppearanceDomain> for AppearanceDomainScope {
    fn from(value: AppearanceDomain) -> Self {
        match value {
            AppearanceDomain::Clothing => Self::Clothing,
            AppearanceDomain::Grooming => Self::Grooming,
            AppearanceDomain::Style => Self::Style,
            AppearanceDomain::Cosmetics => Self::Cosmetics,
            AppearanceDomain::Etiquette => Self::Etiquette,
            AppearanceDomain::Comportment => Self::Comportment,
        }
    }
}
#[rustfmt::skip]
impl AppearanceDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Clothing, Self::Clothing) |
            (Self::Grooming, Self::Grooming) | (Self::Style, Self::Style) |
            (Self::Cosmetics, Self::Cosmetics) | (Self::Etiquette, Self::Etiquette) |
            (Self::Comportment, Self::Comportment)
        )
    }
}
#[rustfmt::skip]
impl From<SafetyDomain> for SafetyDomainScope {
    fn from(value: SafetyDomain) -> Self {
        match value {
            SafetyDomain::Protection => Self::Protection,
            SafetyDomain::Preparedness => Self::Preparedness,
            SafetyDomain::Risk => Self::Risk,
            SafetyDomain::Cybersecurity => Self::Cybersecurity,
            SafetyDomain::Privacy => Self::Privacy,
            SafetyDomain::Disaster => Self::Disaster,
            SafetyDomain::Military => Self::Military,
            SafetyDomain::Deterrence => Self::Deterrence,
        }
    }
}
#[rustfmt::skip]
impl SafetyDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Protection, Self::Protection) |
            (Self::Preparedness, Self::Preparedness) | (Self::Risk, Self::Risk) |
            (Self::Cybersecurity, Self::Cybersecurity) | (Self::Privacy, Self::Privacy) |
            (Self::Disaster, Self::Disaster) | (Self::Military, Self::Military) |
            (Self::Deterrence, Self::Deterrence)
        )
    }
}
#[rustfmt::skip]
impl From<InformationDomain> for InformationDomainScope {
    fn from(value: InformationDomain) -> Self {
        match value {
            InformationDomain::Curation => Self::Curation,
            InformationDomain::RecordKeeping => Self::RecordKeeping,
            InformationDomain::Documentation => Self::Documentation,
            InformationDomain::News => Self::News,
            InformationDomain::Broadcasting => Self::Broadcasting,
            InformationDomain::Archives => Self::Archives,
            InformationDomain::Database => Self::Database,
            InformationDomain::Retrieval => Self::Retrieval,
            InformationDomain::Classification => Self::Classification,
        }
    }
}
#[rustfmt::skip]
impl InformationDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Curation, Self::Curation) |
            (Self::RecordKeeping, Self::RecordKeeping) | (Self::Documentation,
            Self::Documentation) | (Self::News, Self::News) | (Self::Broadcasting,
            Self::Broadcasting) | (Self::Archives, Self::Archives) | (Self::Database,
            Self::Database) | (Self::Retrieval, Self::Retrieval) | (Self::Classification,
            Self::Classification)
        )
    }
}
#[rustfmt::skip]
impl From<HardwareLeaf> for HardwareLeafScope {
    fn from(value: HardwareLeaf) -> Self {
        match value {
            HardwareLeaf::All => Self::All,
            HardwareLeaf::Networking => Self::Networking,
        }
    }
}
#[rustfmt::skip]
impl HardwareLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!((self, scope), (Self::All, _) | (Self::Networking, Self::Networking))
    }
}
#[rustfmt::skip]
impl From<ProgrammingLeaf> for ProgrammingLeafScope {
    fn from(value: ProgrammingLeaf) -> Self {
        match value {
            ProgrammingLeaf::All => Self::All,
            ProgrammingLeaf::TypeSystems => Self::TypeSystems,
            ProgrammingLeaf::Compilation => Self::Compilation,
            ProgrammingLeaf::Parsing => Self::Parsing,
            ProgrammingLeaf::Grammars => Self::Grammars,
            ProgrammingLeaf::CodeGeneration => Self::CodeGeneration,
            ProgrammingLeaf::Metaprogramming => Self::Metaprogramming,
            ProgrammingLeaf::Macros => Self::Macros,
            ProgrammingLeaf::DomainSpecificLanguages => Self::DomainSpecificLanguages,
        }
    }
}
#[rustfmt::skip]
impl ProgrammingLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::TypeSystems, Self::TypeSystems) |
            (Self::Compilation, Self::Compilation) | (Self::Parsing, Self::Parsing) |
            (Self::Grammars, Self::Grammars) | (Self::CodeGeneration,
            Self::CodeGeneration) | (Self::Metaprogramming, Self::Metaprogramming) |
            (Self::Macros, Self::Macros) | (Self::DomainSpecificLanguages,
            Self::DomainSpecificLanguages)
        )
    }
}
#[rustfmt::skip]
impl From<SystemsLeaf> for SystemsLeafScope {
    fn from(value: SystemsLeaf) -> Self {
        match value {
            SystemsLeaf::All => Self::All,
            SystemsLeaf::SystemsProgramming => Self::SystemsProgramming,
            SystemsLeaf::Concurrency => Self::Concurrency,
        }
    }
}
#[rustfmt::skip]
impl SystemsLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::SystemsProgramming,
            Self::SystemsProgramming) | (Self::Concurrency, Self::Concurrency)
        )
    }
}
#[rustfmt::skip]
impl From<DistributedLeaf> for DistributedLeafScope {
    fn from(value: DistributedLeaf) -> Self {
        match value {
            DistributedLeaf::All => Self::All,
            DistributedLeaf::ProtocolDesign => Self::ProtocolDesign,
            DistributedLeaf::EventDrivenArchitecture => Self::EventDrivenArchitecture,
        }
    }
}
#[rustfmt::skip]
impl DistributedLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::ProtocolDesign, Self::ProtocolDesign)
            | (Self::EventDrivenArchitecture, Self::EventDrivenArchitecture)
        )
    }
}
#[rustfmt::skip]
impl From<DataLeaf> for DataLeafScope {
    fn from(value: DataLeaf) -> Self {
        match value {
            DataLeaf::All => Self::All,
            DataLeaf::Persistence => Self::Persistence,
            DataLeaf::Serialization => Self::Serialization,
            DataLeaf::Formats => Self::Formats,
            DataLeaf::Modeling => Self::Modeling,
            DataLeaf::SchemaEvolution => Self::SchemaEvolution,
            DataLeaf::Migration => Self::Migration,
        }
    }
}
#[rustfmt::skip]
impl DataLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Persistence, Self::Persistence) |
            (Self::Serialization, Self::Serialization) | (Self::Formats, Self::Formats) |
            (Self::Modeling, Self::Modeling) | (Self::SchemaEvolution,
            Self::SchemaEvolution) | (Self::Migration, Self::Migration)
        )
    }
}
#[rustfmt::skip]
impl From<IntelligenceLeaf> for IntelligenceLeafScope {
    fn from(value: IntelligenceLeaf) -> Self {
        match value {
            IntelligenceLeaf::All => Self::All,
            IntelligenceLeaf::AgentSystems => Self::AgentSystems,
        }
    }
}
#[rustfmt::skip]
impl IntelligenceLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::AgentSystems, Self::AgentSystems)
        )
    }
}
#[rustfmt::skip]
impl From<SecurityLeaf> for SecurityLeafScope {
    fn from(value: SecurityLeaf) -> Self {
        match value {
            SecurityLeaf::All => Self::All,
            SecurityLeaf::Cryptography => Self::Cryptography,
            SecurityLeaf::Authentication => Self::Authentication,
            SecurityLeaf::Authorization => Self::Authorization,
            SecurityLeaf::SecretsManagement => Self::SecretsManagement,
            SecurityLeaf::Privacy => Self::Privacy,
        }
    }
}
#[rustfmt::skip]
impl SecurityLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Cryptography, Self::Cryptography) |
            (Self::Authentication, Self::Authentication) | (Self::Authorization,
            Self::Authorization) | (Self::SecretsManagement, Self::SecretsManagement) |
            (Self::Privacy, Self::Privacy)
        )
    }
}
#[rustfmt::skip]
impl From<QualityLeaf> for QualityLeafScope {
    fn from(value: QualityLeaf) -> Self {
        match value {
            QualityLeaf::All => Self::All,
            QualityLeaf::Testing => Self::Testing,
        }
    }
}
#[rustfmt::skip]
impl QualityLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!((self, scope), (Self::All, _) | (Self::Testing, Self::Testing))
    }
}
#[rustfmt::skip]
impl From<OperationsLeaf> for OperationsLeafScope {
    fn from(value: OperationsLeaf) -> Self {
        match value {
            OperationsLeaf::All => Self::All,
            OperationsLeaf::BuildSystem => Self::BuildSystem,
            OperationsLeaf::ReleaseEngineering => Self::ReleaseEngineering,
            OperationsLeaf::DependencyManagement => Self::DependencyManagement,
            OperationsLeaf::Deployment => Self::Deployment,
            OperationsLeaf::ConfigurationManagement => Self::ConfigurationManagement,
        }
    }
}
#[rustfmt::skip]
impl OperationsLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::BuildSystem, Self::BuildSystem) |
            (Self::ReleaseEngineering, Self::ReleaseEngineering) |
            (Self::DependencyManagement, Self::DependencyManagement) | (Self::Deployment,
            Self::Deployment) | (Self::ConfigurationManagement,
            Self::ConfigurationManagement)
        )
    }
}
#[rustfmt::skip]
impl From<ObservabilityLeaf> for ObservabilityLeafScope {
    fn from(value: ObservabilityLeaf) -> Self {
        match value {
            ObservabilityLeaf::All => Self::All,
            ObservabilityLeaf::Tracing => Self::Tracing,
        }
    }
}
#[rustfmt::skip]
impl ObservabilityLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!((self, scope), (Self::All, _) | (Self::Tracing, Self::Tracing))
    }
}
#[rustfmt::skip]
impl From<SurfacesLeaf> for SurfacesLeafScope {
    fn from(value: SurfacesLeaf) -> Self {
        match value {
            SurfacesLeaf::All => Self::All,
            SurfacesLeaf::Visualization => Self::Visualization,
            SurfacesLeaf::CommandLineInterfaces => Self::CommandLineInterfaces,
        }
    }
}
#[rustfmt::skip]
impl SurfacesLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Visualization, Self::Visualization) |
            (Self::CommandLineInterfaces, Self::CommandLineInterfaces)
        )
    }
}
#[rustfmt::skip]
impl From<EngineeringLeaf> for EngineeringLeafScope {
    fn from(value: EngineeringLeaf) -> Self {
        match value {
            EngineeringLeaf::All => Self::All,
            EngineeringLeaf::Architecture => Self::Architecture,
            EngineeringLeaf::Design => Self::Design,
            EngineeringLeaf::ApplicationProgrammingInterfaces => {
                Self::ApplicationProgrammingInterfaces
            }
            EngineeringLeaf::Documentation => Self::Documentation,
            EngineeringLeaf::VersionControl => Self::VersionControl,
            EngineeringLeaf::DevelopmentProcess => Self::DevelopmentProcess,
            EngineeringLeaf::Management => Self::Management,
            EngineeringLeaf::Modularity => Self::Modularity,
        }
    }
}
#[rustfmt::skip]
impl EngineeringLeafScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        matches!(
            (self, scope), (Self::All, _) | (Self::Architecture, Self::Architecture) |
            (Self::Design, Self::Design) | (Self::ApplicationProgrammingInterfaces,
            Self::ApplicationProgrammingInterfaces) | (Self::Documentation,
            Self::Documentation) | (Self::VersionControl, Self::VersionControl) |
            (Self::DevelopmentProcess, Self::DevelopmentProcess) | (Self::Management,
            Self::Management) | (Self::Modularity, Self::Modularity)
        )
    }
}
#[rustfmt::skip]
impl From<SoftwareDomain> for SoftwareDomainScope {
    fn from(value: SoftwareDomain) -> Self {
        match value {
            SoftwareDomain::Programming(payload) => Self::Programming(payload.into()),
            SoftwareDomain::Theory => Self::Theory,
            SoftwareDomain::Systems(payload) => Self::Systems(payload.into()),
            SoftwareDomain::Distributed(payload) => Self::Distributed(payload.into()),
            SoftwareDomain::Data(payload) => Self::Data(payload.into()),
            SoftwareDomain::Intelligence(payload) => Self::Intelligence(payload.into()),
            SoftwareDomain::Security(payload) => Self::Security(payload.into()),
            SoftwareDomain::Quality(payload) => Self::Quality(payload.into()),
            SoftwareDomain::Operations(payload) => Self::Operations(payload.into()),
            SoftwareDomain::Observability(payload) => Self::Observability(payload.into()),
            SoftwareDomain::Surfaces(payload) => Self::Surfaces(payload.into()),
            SoftwareDomain::Engineering(payload) => Self::Engineering(payload.into()),
        }
    }
}
#[rustfmt::skip]
impl SoftwareDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        match (self, scope) {
            (Self::All, _) => true,
            (Self::Programming(left), Self::Programming(right)) => {
                left.contains_scope(right)
            }
            (Self::Theory, Self::Theory) => true,
            (Self::Systems(left), Self::Systems(right)) => left.contains_scope(right),
            (Self::Distributed(left), Self::Distributed(right)) => {
                left.contains_scope(right)
            }
            (Self::Data(left), Self::Data(right)) => left.contains_scope(right),
            (Self::Intelligence(left), Self::Intelligence(right)) => {
                left.contains_scope(right)
            }
            (Self::Security(left), Self::Security(right)) => left.contains_scope(right),
            (Self::Quality(left), Self::Quality(right)) => left.contains_scope(right),
            (Self::Operations(left), Self::Operations(right)) => {
                left.contains_scope(right)
            }
            (Self::Observability(left), Self::Observability(right)) => {
                left.contains_scope(right)
            }
            (Self::Surfaces(left), Self::Surfaces(right)) => left.contains_scope(right),
            (Self::Engineering(left), Self::Engineering(right)) => {
                left.contains_scope(right)
            }
            _ => false,
        }
    }
}
#[rustfmt::skip]
impl From<TechnologyDomain> for TechnologyDomainScope {
    fn from(value: TechnologyDomain) -> Self {
        match value {
            TechnologyDomain::Hardware(payload) => Self::Hardware(payload.into()),
            TechnologyDomain::Software(payload) => Self::Software(payload.into()),
        }
    }
}
#[rustfmt::skip]
impl TechnologyDomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        match (self, scope) {
            (Self::All, _) => true,
            (Self::Hardware(left), Self::Hardware(right)) => left.contains_scope(right),
            (Self::Software(left), Self::Software(right)) => left.contains_scope(right),
            _ => false,
        }
    }
}
#[rustfmt::skip]
impl From<Domain> for DomainScope {
    fn from(value: Domain) -> Self {
        match value {
            Domain::All => Self::All,
            Domain::Health(payload) => Self::Health(payload.into()),
            Domain::Food(payload) => Self::Food(payload.into()),
            Domain::Home(payload) => Self::Home(payload.into()),
            Domain::Finance(payload) => Self::Finance(payload.into()),
            Domain::Work(payload) => Self::Work(payload.into()),
            Domain::Craft(payload) => Self::Craft(payload.into()),
            Domain::Knowledge(payload) => Self::Knowledge(payload.into()),
            Domain::Education(payload) => Self::Education(payload.into()),
            Domain::Language(payload) => Self::Language(payload.into()),
            Domain::Art(payload) => Self::Art(payload.into()),
            Domain::Kinship(payload) => Self::Kinship(payload.into()),
            Domain::Selfhood(payload) => Self::Selfhood(payload.into()),
            Domain::Spirituality(payload) => Self::Spirituality(payload.into()),
            Domain::Governance(payload) => Self::Governance(payload.into()),
            Domain::Law(payload) => Self::Law(payload.into()),
            Domain::Community(payload) => Self::Community(payload.into()),
            Domain::Nature(payload) => Self::Nature(payload.into()),
            Domain::Travel(payload) => Self::Travel(payload.into()),
            Domain::Commerce(payload) => Self::Commerce(payload.into()),
            Domain::Leisure(payload) => Self::Leisure(payload.into()),
            Domain::Appearance(payload) => Self::Appearance(payload.into()),
            Domain::Safety(payload) => Self::Safety(payload.into()),
            Domain::Information(payload) => Self::Information(payload.into()),
            Domain::Technology(payload) => Self::Technology(payload.into()),
        }
    }
}
#[rustfmt::skip]
impl DomainScope {
    pub fn contains_scope(&self, scope: &Self) -> bool {
        match (self, scope) {
            (Self::All, Self::All) => true,
            (Self::Health(left), Self::Health(right)) => left.contains_scope(right),
            (Self::Food(left), Self::Food(right)) => left.contains_scope(right),
            (Self::Home(left), Self::Home(right)) => left.contains_scope(right),
            (Self::Finance(left), Self::Finance(right)) => left.contains_scope(right),
            (Self::Work(left), Self::Work(right)) => left.contains_scope(right),
            (Self::Craft(left), Self::Craft(right)) => left.contains_scope(right),
            (Self::Knowledge(left), Self::Knowledge(right)) => left.contains_scope(right),
            (Self::Education(left), Self::Education(right)) => left.contains_scope(right),
            (Self::Language(left), Self::Language(right)) => left.contains_scope(right),
            (Self::Art(left), Self::Art(right)) => left.contains_scope(right),
            (Self::Kinship(left), Self::Kinship(right)) => left.contains_scope(right),
            (Self::Selfhood(left), Self::Selfhood(right)) => left.contains_scope(right),
            (Self::Spirituality(left), Self::Spirituality(right)) => {
                left.contains_scope(right)
            }
            (Self::Governance(left), Self::Governance(right)) => {
                left.contains_scope(right)
            }
            (Self::Law(left), Self::Law(right)) => left.contains_scope(right),
            (Self::Community(left), Self::Community(right)) => left.contains_scope(right),
            (Self::Nature(left), Self::Nature(right)) => left.contains_scope(right),
            (Self::Travel(left), Self::Travel(right)) => left.contains_scope(right),
            (Self::Commerce(left), Self::Commerce(right)) => left.contains_scope(right),
            (Self::Leisure(left), Self::Leisure(right)) => left.contains_scope(right),
            (Self::Appearance(left), Self::Appearance(right)) => {
                left.contains_scope(right)
            }
            (Self::Safety(left), Self::Safety(right)) => left.contains_scope(right),
            (Self::Information(left), Self::Information(right)) => {
                left.contains_scope(right)
            }
            (Self::Technology(left), Self::Technology(right)) => {
                left.contains_scope(right)
            }
            _ => false,
        }
    }
    pub fn contains_domain(&self, domain: &Domain) -> bool {
        self.contains_scope(&domain.clone().into())
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for DomainScope {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for DomainScope {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainScopes(Vec<DomainScope>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ScopeSet(Vec<DomainScope>);

#[rustfmt::skip]
impl DomainScopes {
    pub fn new(payload: Vec<DomainScope>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DomainScope> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DomainScope> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DomainScope>> for DomainScopes {
    fn from(payload: Vec<DomainScope>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ScopeSet {
    pub fn new(payload: Vec<DomainScope>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DomainScope> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DomainScope> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DomainScope>> for ScopeSet {
    fn from(payload: Vec<DomainScope>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Domain {
    pub fn health(payload: HealthDomain) -> Self {
        Self::Health(payload)
    }
    pub fn food(payload: FoodDomain) -> Self {
        Self::Food(payload)
    }
    pub fn home(payload: HomeDomain) -> Self {
        Self::Home(payload)
    }
    pub fn finance(payload: FinanceDomain) -> Self {
        Self::Finance(payload)
    }
    pub fn work(payload: WorkDomain) -> Self {
        Self::Work(payload)
    }
    pub fn craft(payload: CraftDomain) -> Self {
        Self::Craft(payload)
    }
    pub fn knowledge(payload: KnowledgeDomain) -> Self {
        Self::Knowledge(payload)
    }
    pub fn education(payload: EducationDomain) -> Self {
        Self::Education(payload)
    }
    pub fn language(payload: LanguageDomain) -> Self {
        Self::Language(payload)
    }
    pub fn art(payload: ArtDomain) -> Self {
        Self::Art(payload)
    }
    pub fn kinship(payload: KinshipDomain) -> Self {
        Self::Kinship(payload)
    }
    pub fn selfhood(payload: SelfhoodDomain) -> Self {
        Self::Selfhood(payload)
    }
    pub fn spirituality(payload: SpiritualityDomain) -> Self {
        Self::Spirituality(payload)
    }
    pub fn governance(payload: GovernanceDomain) -> Self {
        Self::Governance(payload)
    }
    pub fn law(payload: LawDomain) -> Self {
        Self::Law(payload)
    }
    pub fn community(payload: CommunityDomain) -> Self {
        Self::Community(payload)
    }
    pub fn nature(payload: NatureDomain) -> Self {
        Self::Nature(payload)
    }
    pub fn travel(payload: TravelDomain) -> Self {
        Self::Travel(payload)
    }
    pub fn commerce(payload: CommerceDomain) -> Self {
        Self::Commerce(payload)
    }
    pub fn leisure(payload: LeisureDomain) -> Self {
        Self::Leisure(payload)
    }
    pub fn appearance(payload: AppearanceDomain) -> Self {
        Self::Appearance(payload)
    }
    pub fn safety(payload: SafetyDomain) -> Self {
        Self::Safety(payload)
    }
    pub fn information(payload: InformationDomain) -> Self {
        Self::Information(payload)
    }
    pub fn technology(payload: TechnologyDomain) -> Self {
        Self::Technology(payload)
    }
}

#[rustfmt::skip]
impl TechnologyDomain {
    pub fn hardware(payload: HardwareLeaf) -> Self {
        Self::Hardware(payload)
    }
    pub fn software(payload: SoftwareDomain) -> Self {
        Self::Software(payload)
    }
}

#[rustfmt::skip]
impl SoftwareDomain {
    pub fn programming(payload: ProgrammingLeaf) -> Self {
        Self::Programming(payload)
    }
    pub fn systems(payload: SystemsLeaf) -> Self {
        Self::Systems(payload)
    }
    pub fn distributed(payload: DistributedLeaf) -> Self {
        Self::Distributed(payload)
    }
    pub fn data(payload: DataLeaf) -> Self {
        Self::Data(payload)
    }
    pub fn intelligence(payload: IntelligenceLeaf) -> Self {
        Self::Intelligence(payload)
    }
    pub fn security(payload: SecurityLeaf) -> Self {
        Self::Security(payload)
    }
    pub fn quality(payload: QualityLeaf) -> Self {
        Self::Quality(payload)
    }
    pub fn operations(payload: OperationsLeaf) -> Self {
        Self::Operations(payload)
    }
    pub fn observability(payload: ObservabilityLeaf) -> Self {
        Self::Observability(payload)
    }
    pub fn surfaces(payload: SurfacesLeaf) -> Self {
        Self::Surfaces(payload)
    }
    pub fn engineering(payload: EngineeringLeaf) -> Self {
        Self::Engineering(payload)
    }
}

#[rustfmt::skip]
impl From<HealthDomain> for Domain {
    fn from(payload: HealthDomain) -> Self {
        Self::Health(payload)
    }
}

#[rustfmt::skip]
impl From<FoodDomain> for Domain {
    fn from(payload: FoodDomain) -> Self {
        Self::Food(payload)
    }
}

#[rustfmt::skip]
impl From<HomeDomain> for Domain {
    fn from(payload: HomeDomain) -> Self {
        Self::Home(payload)
    }
}

#[rustfmt::skip]
impl From<FinanceDomain> for Domain {
    fn from(payload: FinanceDomain) -> Self {
        Self::Finance(payload)
    }
}

#[rustfmt::skip]
impl From<WorkDomain> for Domain {
    fn from(payload: WorkDomain) -> Self {
        Self::Work(payload)
    }
}

#[rustfmt::skip]
impl From<CraftDomain> for Domain {
    fn from(payload: CraftDomain) -> Self {
        Self::Craft(payload)
    }
}

#[rustfmt::skip]
impl From<KnowledgeDomain> for Domain {
    fn from(payload: KnowledgeDomain) -> Self {
        Self::Knowledge(payload)
    }
}

#[rustfmt::skip]
impl From<EducationDomain> for Domain {
    fn from(payload: EducationDomain) -> Self {
        Self::Education(payload)
    }
}

#[rustfmt::skip]
impl From<LanguageDomain> for Domain {
    fn from(payload: LanguageDomain) -> Self {
        Self::Language(payload)
    }
}

#[rustfmt::skip]
impl From<ArtDomain> for Domain {
    fn from(payload: ArtDomain) -> Self {
        Self::Art(payload)
    }
}

#[rustfmt::skip]
impl From<KinshipDomain> for Domain {
    fn from(payload: KinshipDomain) -> Self {
        Self::Kinship(payload)
    }
}

#[rustfmt::skip]
impl From<SelfhoodDomain> for Domain {
    fn from(payload: SelfhoodDomain) -> Self {
        Self::Selfhood(payload)
    }
}

#[rustfmt::skip]
impl From<SpiritualityDomain> for Domain {
    fn from(payload: SpiritualityDomain) -> Self {
        Self::Spirituality(payload)
    }
}

#[rustfmt::skip]
impl From<GovernanceDomain> for Domain {
    fn from(payload: GovernanceDomain) -> Self {
        Self::Governance(payload)
    }
}

#[rustfmt::skip]
impl From<LawDomain> for Domain {
    fn from(payload: LawDomain) -> Self {
        Self::Law(payload)
    }
}

#[rustfmt::skip]
impl From<CommunityDomain> for Domain {
    fn from(payload: CommunityDomain) -> Self {
        Self::Community(payload)
    }
}

#[rustfmt::skip]
impl From<NatureDomain> for Domain {
    fn from(payload: NatureDomain) -> Self {
        Self::Nature(payload)
    }
}

#[rustfmt::skip]
impl From<TravelDomain> for Domain {
    fn from(payload: TravelDomain) -> Self {
        Self::Travel(payload)
    }
}

#[rustfmt::skip]
impl From<CommerceDomain> for Domain {
    fn from(payload: CommerceDomain) -> Self {
        Self::Commerce(payload)
    }
}

#[rustfmt::skip]
impl From<LeisureDomain> for Domain {
    fn from(payload: LeisureDomain) -> Self {
        Self::Leisure(payload)
    }
}

#[rustfmt::skip]
impl From<AppearanceDomain> for Domain {
    fn from(payload: AppearanceDomain) -> Self {
        Self::Appearance(payload)
    }
}

#[rustfmt::skip]
impl From<SafetyDomain> for Domain {
    fn from(payload: SafetyDomain) -> Self {
        Self::Safety(payload)
    }
}

#[rustfmt::skip]
impl From<InformationDomain> for Domain {
    fn from(payload: InformationDomain) -> Self {
        Self::Information(payload)
    }
}

#[rustfmt::skip]
impl From<TechnologyDomain> for Domain {
    fn from(payload: TechnologyDomain) -> Self {
        Self::Technology(payload)
    }
}

#[rustfmt::skip]
impl From<HardwareLeaf> for TechnologyDomain {
    fn from(payload: HardwareLeaf) -> Self {
        Self::Hardware(payload)
    }
}

#[rustfmt::skip]
impl From<SoftwareDomain> for TechnologyDomain {
    fn from(payload: SoftwareDomain) -> Self {
        Self::Software(payload)
    }
}

#[rustfmt::skip]
impl From<ProgrammingLeaf> for SoftwareDomain {
    fn from(payload: ProgrammingLeaf) -> Self {
        Self::Programming(payload)
    }
}

#[rustfmt::skip]
impl From<SystemsLeaf> for SoftwareDomain {
    fn from(payload: SystemsLeaf) -> Self {
        Self::Systems(payload)
    }
}

#[rustfmt::skip]
impl From<DistributedLeaf> for SoftwareDomain {
    fn from(payload: DistributedLeaf) -> Self {
        Self::Distributed(payload)
    }
}

#[rustfmt::skip]
impl From<DataLeaf> for SoftwareDomain {
    fn from(payload: DataLeaf) -> Self {
        Self::Data(payload)
    }
}

#[rustfmt::skip]
impl From<IntelligenceLeaf> for SoftwareDomain {
    fn from(payload: IntelligenceLeaf) -> Self {
        Self::Intelligence(payload)
    }
}

#[rustfmt::skip]
impl From<SecurityLeaf> for SoftwareDomain {
    fn from(payload: SecurityLeaf) -> Self {
        Self::Security(payload)
    }
}

#[rustfmt::skip]
impl From<QualityLeaf> for SoftwareDomain {
    fn from(payload: QualityLeaf) -> Self {
        Self::Quality(payload)
    }
}

#[rustfmt::skip]
impl From<OperationsLeaf> for SoftwareDomain {
    fn from(payload: OperationsLeaf) -> Self {
        Self::Operations(payload)
    }
}

#[rustfmt::skip]
impl From<ObservabilityLeaf> for SoftwareDomain {
    fn from(payload: ObservabilityLeaf) -> Self {
        Self::Observability(payload)
    }
}

#[rustfmt::skip]
impl From<SurfacesLeaf> for SoftwareDomain {
    fn from(payload: SurfacesLeaf) -> Self {
        Self::Surfaces(payload)
    }
}

#[rustfmt::skip]
impl From<EngineeringLeaf> for SoftwareDomain {
    fn from(payload: EngineeringLeaf) -> Self {
        Self::Engineering(payload)
    }
}
